// Share/export helpers. Generates a branded PDF when the native modules are
// present (expo-print / expo-sharing, after the next build); otherwise falls
// back to the built-in Share sheet with a formatted text version — so this works
// TODAY over-the-air and upgrades to real PDFs automatically once rebuilt.
import { Share } from 'react-native';

let Print: any = null;
let Sharing: any = null;
try { Print = require('expo-print'); } catch { /* not in this build yet */ }
try { Sharing = require('expo-sharing'); } catch { /* optional */ }

export const pdfExportAvailable = () => !!Print;

export async function shareDoc(html: string, text: string, title: string): Promise<'pdf' | 'text'> {
  if (Print?.printToFileAsync) {
    try {
      const { uri } = await Print.printToFileAsync({ html });
      if (uri && Sharing?.shareAsync) {
        const ok = Sharing.isAvailableAsync ? await Sharing.isAvailableAsync() : true;
        if (ok) { await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: title, UTI: 'com.adobe.pdf' }); return 'pdf'; }
      }
    } catch { /* fall through to text */ }
  }
  try { await Share.share({ message: text, title }); } catch { /* ignore */ }
  return 'text';
}

const page = (title: string, body: string, brand = 'Repple') =>
  `<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>
   body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#0f172a;padding:26px;margin:0}
   .h{background:linear-gradient(135deg,#2dd4bf,#0d9488);color:#fff;padding:18px 22px;border-radius:14px}
   .h h1{margin:0;font-size:22px} .h p{margin:4px 0 0;opacity:.9;font-size:13px}
   table{width:100%;border-collapse:collapse;margin-top:18px;font-size:14px}
   th,td{text-align:left;padding:9px 8px;border-bottom:1px solid #e2e8f0}
   th{color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.5px}
   .r{text-align:right} .tot td{font-weight:800;border-top:2px solid #0f172a}
   .foot{margin-top:20px;color:#94a3b8;font-size:11px}
   </style></head><body><div class="h"><h1>${title}</h1><p>${brand}</p></div>${body}<p class="foot">Generated by ${brand}</p></body></html>`;

export interface PlanMealRow { slot: string; name: string; K: number; P: number; C: number; F: number }

export function mealPlanDoc(name: string, targetKcal: number, meals: PlanMealRow[], avoid: string[] = [], brand = 'Repple'): { html: string; text: string } {
  const first = (name || '').split(' ')[0] || 'Your';
  const rows = meals.map((m) => `<tr><td><b>${m.slot}</b><br><span style="color:#64748b">${m.name}</span></td><td class="r">${m.K}</td><td class="r">${m.P}g</td><td class="r">${m.C}g</td><td class="r">${m.F}g</td></tr>`).join('');
  const totK = meals.reduce((a, m) => a + m.K, 0), totP = meals.reduce((a, m) => a + m.P, 0), totC = meals.reduce((a, m) => a + m.C, 0), totF = meals.reduce((a, m) => a + m.F, 0);
  const avoidLine = avoid.length ? `<p style="color:#64748b;font-size:13px;margin-top:10px">Excludes: ${avoid.join(', ')}</p>` : '';
  const body = `<h2 style="margin-top:20px">${first}'s meal plan</h2><p style="color:#64748b;margin:0">Daily target ~${targetKcal.toLocaleString()} kcal</p>${avoidLine}
    <table><tr><th>Meal</th><th class="r">Kcal</th><th class="r">P</th><th class="r">C</th><th class="r">F</th></tr>
    ${rows}<tr class="tot"><td>Total</td><td class="r">${totK}</td><td class="r">${totP}g</td><td class="r">${totC}g</td><td class="r">${totF}g</td></tr></table>`;
  const text = `${first}'s meal plan (${brand}) — target ~${targetKcal} kcal\n` +
    meals.map((m) => `• ${m.slot}: ${m.name} — ${m.K} kcal (P${m.P}/C${m.C}/F${m.F})`).join('\n') +
    `\nTotal: ${totK} kcal · P${totP} C${totC} F${totF}` + (avoid.length ? `\nExcludes: ${avoid.join(', ')}` : '');
  return { html: page('Meal Plan', body, brand), text };
}

export interface ProgressRow { date: string; weightKg: number; bodyFatPct: number; muscleKg: number }

export function progressDoc(name: string, rows: ProgressRow[], brand = 'Repple'): { html: string; text: string } {
  const first = (name || '').split(' ')[0] || 'Your';
  const tr = rows.map((r) => `<tr><td>${r.date}</td><td class="r">${r.weightKg}</td><td class="r">${r.bodyFatPct}%</td><td class="r">${r.muscleKg}</td></tr>`).join('');
  const f = rows[0], l = rows[rows.length - 1];
  const delta = f && l ? `<p style="color:#64748b;margin:0">Since ${f.date}: weight ${(l.weightKg - f.weightKg).toFixed(1)}kg · body fat ${(l.bodyFatPct - f.bodyFatPct).toFixed(1)}% · muscle ${(l.muscleKg - f.muscleKg).toFixed(1)}kg</p>` : '';
  const body = `<h2 style="margin-top:20px">${first}'s progress</h2>${delta}
    <table><tr><th>Date</th><th class="r">Weight</th><th class="r">Body fat</th><th class="r">Muscle</th></tr>${tr}</table>`;
  const text = `${first}'s progress (${brand})\n` + rows.map((r) => `• ${r.date}: ${r.weightKg}kg · ${r.bodyFatPct}% BF · ${r.muscleKg}kg muscle`).join('\n');
  return { html: page('Progress', body, brand), text };
}
