// ── Procedural meal engine ───────────────────────────────────────────────────
// Ported from the validated prototype (part14). Meals are generated by combining
// components, so each diet has hundreds of options per slot. Every generated meal
// carries real macros + ingredients (with grocery departments) + method steps, so
// recipes and the grocery list work automatically.
//
// Pure & UI-free: identical on client and server, trivially unit-testable. The RN
// screens render these objects; they never reimplement the math.
import type { Diet, BodyStats } from './types';
import { macrosFor, applyCoachAdjust, type CoachAdjust } from './nutrition';
import type { EnergyPlan } from './goalEnergy';

export type Slot = 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack';
export const DEPTS = [
  'Meat & Seafood', 'Dairy & Eggs', 'Vegetables', 'Fruits',
  'Grains & Bread', 'Nuts & Seeds', 'Fats & Oils', 'Pantry & Other',
] as const;
export type Dept = typeof DEPTS[number];
export const DEPT_ICO: Record<Dept, string> = {
  'Meat & Seafood': '🥩', 'Dairy & Eggs': '🥚', 'Vegetables': '🥦', 'Fruits': '🍎',
  'Grains & Bread': '🍞', 'Nuts & Seeds': '🥜', 'Fats & Oils': '🫒', 'Pantry & Other': '🧂',
};

type Ing = [item: string, qty: number, unit: string, dept: Dept];
interface Comp {
  n: string; ico?: string; k: number; p: number; c: number; f: number;
  ing: Ing[]; step?: string; d: Diet[];
}
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const forDiet = (arr: Comp[], diet: Diet) => arr.filter((x) => x.d.includes(diet));

export type Allergen = 'dairy' | 'gluten' | 'nuts' | 'shellfish' | 'egg' | 'soy';
export const ALLERGENS: { id: Allergen; label: string }[] = [
  { id: 'dairy', label: 'Dairy' }, { id: 'gluten', label: 'Gluten' }, { id: 'nuts', label: 'Nuts' },
  { id: 'shellfish', label: 'Shellfish' }, { id: 'egg', label: 'Egg' }, { id: 'soy', label: 'Soy' },
];
/**
 * Compound names whose head word is not the thing it looks like.
 *
 * The dairy test used to be a bare `/…|butter|milk|…/` with no word boundaries
 * anywhere in it, so `butternut squash` (a vegetable), `peanut butter`,
 * `almond butter` and `nut-butter toast` (all nuts) and the three `Soy milk`
 * breakfasts (a bean) were every one of them tagged dairy. A member who ticked
 * Dairy silently lost squash, nut butters and the vegan soy-milk meals from
 * their pool, and where that emptied a pool `allergenGapNote` told them "Your
 * plan still contains dairy" about a plan that contained none.
 *
 * That is the one warning somebody with a real allergy has to be able to read
 * once and believe, so the fix is in two halves and both are needed. This strip
 * removes the compounds, and the boundaries below stop `butternut` reading as
 * `butter`. Boundaries alone would not have been enough: `peanut butter` has a
 * genuine standalone `butter` in it.
 *
 * Deliberately conservative in the direction that matters. It removes only a
 * named plant word immediately in front of a dairy word; anything it does not
 * recognise still reaches the dairy test, so a new ingredient errs towards
 * being flagged rather than towards being fed to somebody.
 */
const DAIRY_LOOKALIKE = /\b(peanut|almond|cashew|hazelnut|pistachio|pecan|walnut|macadamia|nut|seed|sunflower|sesame|coconut|soy|soya|oat|rice|hemp|pea|cocoa|shea)[\s-]+(butters?|milks?|creams?|yogurts?|yoghurts?|cheeses?)\b/g;
function componentAllergens(comp: Comp): Allergen[] {
  const text = (comp.n + ' ' + comp.ing.map((i) => i[0]).join(' ')).toLowerCase();
  const out: Allergen[] = [];
  // `buttermilk` is named because the boundaries that save `butternut` would
  // otherwise lose it: it is one word, and neither `\bbutter\b` nor `\bmilk\b`
  // is inside it.
  if (/\b(milk|buttermilk|yogurt|yoghurt|cheese|whey|butter|creamy?|greek)\b/.test(text.replace(DAIRY_LOOKALIKE, ' ')))
    out.push('dairy');
  if (/bread|pasta|couscous|wheat|barley|\brye|tortilla|wrap|\bbun|noodle|cracker|\boat|granola|cereal|toast/.test(text)) out.push('gluten');
  if (/almond|walnut|cashew|pecan|macadamia|peanut|hazelnut|pistachio|\bnut|trail mix/.test(text)) out.push('nuts');
  if (/prawn|shrimp|crab|lobster|scallop|mussel|oyster|shellfish/.test(text)) out.push('shellfish');
  if (/\begg/.test(text)) out.push('egg');
  if (/tofu|tempeh|edamame|\bsoy|miso/.test(text)) out.push('soy');
  return out;
}
/**
 * The components of a pool that honour the exclusions — and the fallback, said
 * out loud instead of buried.
 *
 * ── What was wrong ────────────────────────────────────────────────────────
 *
 * This was `return filtered.length ? filtered : pool;` and nothing anywhere
 * told the member. On the one screen where a quiet failure is least acceptable,
 * an allergen that emptied a required pool was silently abandoned and the
 * planner went on building meals out of the very components it had been asked
 * to leave out. A member who ticked Dairy got a plan with dairy in it, drawn
 * and priced and shopped for, with nothing on screen to suggest anything had
 * happened.
 *
 * ── Why the fallback survives ─────────────────────────────────────────────
 *
 * Because the alternative is worse in a way that is harder to see. The pools
 * are mixed-radix dimensions and every slot needs one component from each; an
 * empty dimension means there is NO meal in this diet and this slot that
 * honours every exclusion. Returning nothing would make `mealAt` build a meal
 * out of nulls — it reads `base.step`, `pr.n`, `a.ico` straight off the parts —
 * and a screen that crashes tells the member even less than one that lies.
 *
 * So the pool still falls back AND `poolGaps` names exactly which exclusions
 * could not be honoured, `mealAllergens` says which of them are actually in a
 * given meal, and app/(client)/nutrition.tsx prints both. The plan is drawn,
 * and it is drawn with a warning on it rather than as though nothing were
 * wrong.
 */
function poolFilter(pool: Comp[], avoid: Allergen[]): Comp[] {
  if (!avoid.length) return pool;
  const filtered = pool.filter((cp) => !componentAllergens(cp).some((a) => avoid.includes(a)));
  return filtered.length ? filtered : pool;
}

/**
 * The exclusions this diet and slot cannot honour, because honouring them would
 * leave a required component pool with nothing in it.
 *
 * Per allergen rather than per pool, because that is the sentence a member
 * needs: "we could not keep dairy out of your breakfasts" is actionable and
 * "component dimension 2 is empty" is not. An allergen is reported when
 * removing it ALONE would empty a pool, so a member excluding four things is
 * told which of the four is the problem rather than being handed all four back.
 */
export function poolGaps(diet: Diet, slot: Slot, avoid: Allergen[] = []): Allergen[] {
  if (!avoid.length) return [];
  const pools = slot === 'Breakfast' ? [BREK_BASE, BREK_TOP, BREK_BOOST, BREK_STYLE]
    : slot === 'Snack' ? [SNACK_A, SNACK_B, SNACK_PREP]
    : [PROTEINS, CARBS, VEGS, FLAVORS];
  const out: Allergen[] = [];
  for (const a of avoid) {
    const empties = pools.some((pool) => {
      const forThisDiet = forDiet(pool, diet);
      if (!forThisDiet.length) return false;   // the diet already empties it; not this allergen's doing
      return !forThisDiet.some((cp) => !componentAllergens(cp).includes(a));
    });
    if (empties) out.push(a);
  }
  // ── the exclusions that only fail TOGETHER ──────────────────────────────
  //
  // The loop above asks each allergen ALONE, and `poolFilter` filters against
  // the whole list AT ONCE. Those are different questions, and the gap between
  // them is silent: dairy alone may leave a pool with something in it, gluten
  // alone may too, and dairy-and-gluten together may empty it. `poolFilter`
  // then falls back to the UNFILTERED pool — the fallback whose entire
  // justification, twenty lines up, is that the plan is "drawn with a warning
  // on it rather than as though nothing were wrong" — while this function
  // returned nothing to warn with. The member got a plan that had quietly
  // ignored their filter, with no banner anywhere.
  //
  // So the same question `poolFilter` actually asks is asked here: does the
  // whole exclusion list empty a required pool? When it does, every exclusion
  // still standing is named — none of them can be singled out as the culprit,
  // because it is the combination, and the member needs to know the filter was
  // not honoured rather than which half to blame.
  const combinedEmpties = pools.some((pool) => {
    const forThisDiet = forDiet(pool, diet);
    if (!forThisDiet.length) return false;
    return !forThisDiet.some((cp) => !componentAllergens(cp).some((a) => avoid.includes(a)));
  });
  if (combinedEmpties) for (const a of avoid) if (!out.includes(a)) out.push(a);
  return out;
}

/** Every exclusion that cannot be honoured across a whole day's slots. */
export function planGaps(diet: Diet, slots: Slot[], avoid: Allergen[] = []): Allergen[] {
  const seen = new Set<Allergen>();
  for (const slot of slots) for (const a of poolGaps(diet, slot, avoid)) seen.add(a);
  return [...seen];
}

/**
 * Which of the excluded allergens are actually present in a generated meal.
 *
 * The per-meal half of the same honesty. `poolGaps` says the filter could not
 * be honoured somewhere in the slot; this says whether THIS meal, the one on
 * screen with a name and a picture, contains the thing the member asked to
 * avoid. A member is owed the flag on the row they are about to cook, not only
 * a warning at the top of the screen.
 *
 * Read off the meal's own name and ingredients with the same matcher the
 * components go through, so a meal assembled from parts is tested as the dish
 * it became.
 */
export function mealAllergens(meal: { n: string; ing: Ing[] }, avoid: Allergen[] = []): Allergen[] {
  if (!avoid.length) return [];
  const found = componentAllergens({ n: meal.n, k: 0, p: 0, c: 0, f: 0, ing: meal.ing, d: [] });
  return avoid.filter((a) => found.includes(a));
}

/** How an allergen reads in a sentence. The pills already have labels; this is
 *  for prose, where 'Nuts' mid-sentence reads as a proper noun. */
export function allergenLabel(a: Allergen): string {
  return (ALLERGENS.find((x) => x.id === a)?.label ?? a).toLowerCase();
}

/**
 * What to say when an exclusion could not be honoured, or null when they all
 * were.
 *
 * The wording has one job: make it unmistakable that the plan below contains
 * something the member asked to keep out, and say which. It does not apologise
 * and it does not hedge — somebody with a real allergy has to be able to read
 * this once and know.
 */
export function allergenGapNote(gaps: Allergen[]): string | null {
  if (!gaps.length) return null;
  const names = gaps.map(allergenLabel);
  const list = names.length === 1 ? names[0]
    : `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}`;
  return `Your plan still contains ${list}. There are not enough ${list.includes('and') ? 'suitable components' : `${list}-free components`} in this diet to build every meal without ${names.length === 1 ? 'it' : 'them'}, so the meals below have been built anyway and are marked where ${names.length === 1 ? 'it appears' : 'they appear'}. Check every dish before you cook it.`;
}

// ── LUNCH / DINNER components ──
const PROTEINS: Comp[] = [
  { n: 'grilled chicken', ico: '🍗', k: 220, p: 40, c: 0, f: 6,  ing: [['Chicken breast', 180, 'g', 'Meat & Seafood']], d: ['meat', 'paleo', 'keto'] },
  { n: 'salmon',          ico: '🐟', k: 300, p: 34, c: 0, f: 18, ing: [['Salmon fillet', 160, 'g', 'Meat & Seafood']], d: ['meat', 'paleo', 'keto'] },
  { n: 'lean beef',       ico: '🥩', k: 250, p: 36, c: 0, f: 11, ing: [['Lean beef', 170, 'g', 'Meat & Seafood']], d: ['meat', 'paleo', 'keto'] },
  { n: 'turkey',          ico: '🦃', k: 200, p: 38, c: 0, f: 5,  ing: [['Turkey breast', 170, 'g', 'Meat & Seafood']], d: ['meat', 'paleo', 'keto'] },
  { n: 'white fish',      ico: '🐟', k: 160, p: 35, c: 0, f: 2,  ing: [['Cod fillet', 180, 'g', 'Meat & Seafood']], d: ['meat', 'paleo', 'keto'] },
  { n: 'prawns',          ico: '🦐', k: 170, p: 30, c: 2, f: 4,  ing: [['Prawns', 150, 'g', 'Meat & Seafood']], d: ['meat', 'paleo', 'keto'] },
  { n: 'tofu',            ico: '🌱', k: 180, p: 20, c: 6, f: 10, ing: [['Firm tofu', 180, 'g', 'Pantry & Other']], d: ['vegan', 'vegetarian'] },
  { n: 'tempeh',          ico: '🌱', k: 200, p: 22, c: 8, f: 11, ing: [['Tempeh', 150, 'g', 'Pantry & Other']], d: ['vegan', 'vegetarian'] },
  { n: 'chickpeas',       ico: '🫘', k: 210, p: 12, c: 34, f: 4, ing: [['Chickpeas', 200, 'g', 'Pantry & Other']], d: ['vegan', 'vegetarian'] },
  { n: 'lentils',         ico: '🫘', k: 200, p: 16, c: 32, f: 2, ing: [['Cooked lentils', 200, 'g', 'Pantry & Other']], d: ['vegan', 'vegetarian'] },
  { n: 'black beans',     ico: '🫘', k: 200, p: 13, c: 34, f: 2, ing: [['Black beans', 200, 'g', 'Pantry & Other']], d: ['vegan', 'vegetarian'] },
  { n: 'seitan',          ico: '🌱', k: 190, p: 36, c: 8, f: 2,  ing: [['Seitan', 150, 'g', 'Pantry & Other']], d: ['vegan', 'vegetarian'] },
  { n: 'halloumi',        ico: '🧀', k: 260, p: 19, c: 2, f: 20, ing: [['Halloumi', 90, 'g', 'Dairy & Eggs']], d: ['vegetarian', 'keto'] },
  { n: 'paneer',          ico: '🧀', k: 265, p: 18, c: 4, f: 20, ing: [['Paneer', 120, 'g', 'Dairy & Eggs']], d: ['vegetarian', 'keto'] },
  { n: 'eggs',            ico: '🍳', k: 210, p: 18, c: 1, f: 15, ing: [['Eggs', 3, '', 'Dairy & Eggs']], d: ['vegetarian', 'paleo', 'keto', 'meat'] },
  { n: 'edamame',         ico: '🫛', k: 150, p: 14, c: 12, f: 6, ing: [['Edamame', 150, 'g', 'Vegetables']], d: ['vegan', 'vegetarian'] },
];
const CARBS: Comp[] = [
  { n: 'white rice',       k: 180, p: 4, c: 39, f: 1, ing: [['White rice (dry)', 60, 'g', 'Grains & Bread']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'brown rice',       k: 175, p: 4, c: 37, f: 1, ing: [['Brown rice (dry)', 60, 'g', 'Grains & Bread']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'jasmine rice',     k: 180, p: 4, c: 40, f: 0, ing: [['Jasmine rice (dry)', 60, 'g', 'Grains & Bread']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'quinoa',           k: 170, p: 6, c: 30, f: 3, ing: [['Quinoa (dry)', 55, 'g', 'Grains & Bread']], d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'wholewheat pasta', k: 200, p: 7, c: 42, f: 1, ing: [['Wholewheat pasta', 70, 'g', 'Grains & Bread']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'couscous',         k: 180, p: 6, c: 38, f: 0, ing: [['Couscous', 60, 'g', 'Grains & Bread']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'soba noodles',     k: 190, p: 8, c: 40, f: 1, ing: [['Soba noodles', 70, 'g', 'Grains & Bread']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'sweet potato',     k: 150, p: 3, c: 34, f: 0, ing: [['Sweet potato', 200, 'g', 'Vegetables']], d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'butternut squash', k: 110, p: 2, c: 26, f: 0, ing: [['Butternut squash', 220, 'g', 'Vegetables']], d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'roast potatoes',   k: 180, p: 4, c: 36, f: 3, ing: [['Potatoes', 220, 'g', 'Vegetables']], d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'cauliflower rice',  k: 45, p: 3, c: 6, f: 1,  ing: [['Cauliflower rice', 200, 'g', 'Vegetables']], d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'zucchini noodles',  k: 40, p: 3, c: 6, f: 1,  ing: [['Courgette', 250, 'g', 'Vegetables']], d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'cauliflower mash',  k: 90, p: 4, c: 9, f: 5,  ing: [['Cauliflower', 250, 'g', 'Vegetables'], ['Butter', 10, 'g', 'Fats & Oils']], d: ['vegetarian', 'paleo', 'keto'] },
  { n: 'leafy green base',  k: 35, p: 3, c: 5, f: 1,  ing: [['Mixed leaves', 80, 'g', 'Vegetables']], d: ['meat', 'vegetarian', 'keto'] },
];
const VEGS: Comp[] = ([
  { n: 'broccoli',         ing: [['Broccoli', 120, 'g', 'Vegetables']], k: 40, p: 4, c: 6, f: 0 },
  { n: 'asparagus',        ing: [['Asparagus', 100, 'g', 'Vegetables']], k: 30, p: 3, c: 4, f: 0 },
  { n: 'green beans',      ing: [['Green beans', 120, 'g', 'Vegetables']], k: 40, p: 2, c: 7, f: 0 },
  { n: 'spinach',          ing: [['Spinach', 80, 'g', 'Vegetables']], k: 25, p: 3, c: 3, f: 0 },
  { n: 'roasted peppers',  ing: [['Bell peppers', 120, 'g', 'Vegetables']], k: 45, p: 1, c: 9, f: 0 },
  { n: 'courgette',        ing: [['Courgette', 150, 'g', 'Vegetables']], k: 35, p: 2, c: 6, f: 0 },
  { n: 'cauliflower',      ing: [['Cauliflower', 150, 'g', 'Vegetables']], k: 40, p: 3, c: 7, f: 0 },
  { n: 'kale',             ing: [['Kale', 80, 'g', 'Vegetables']], k: 35, p: 3, c: 5, f: 0 },
  { n: 'garden salad',     ing: [['Salad leaves', 60, 'g', 'Vegetables'], ['Cherry tomatoes', 80, 'g', 'Vegetables']], k: 40, p: 2, c: 7, f: 0 },
  { n: 'roast vegetables', ing: [['Mixed vegetables', 200, 'g', 'Vegetables']], k: 80, p: 3, c: 14, f: 1 },
  { n: 'bok choy',         ing: [['Bok choy', 120, 'g', 'Vegetables']], k: 25, p: 2, c: 4, f: 0 },
  { n: 'mushrooms',        ing: [['Mushrooms', 120, 'g', 'Vegetables']], k: 30, p: 4, c: 4, f: 0 },
] as Omit<Comp, 'd'>[]).map((v) => ({ ...v, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] as Diet[] }));
const FLAVORS: Comp[] = [
  { n: 'Mediterranean', k: 90, p: 0, c: 1, f: 10, ing: [['Olive oil', 10, 'ml', 'Fats & Oils'], ['Lemon', 0.5, '', 'Fruits']], d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'Cajun',         k: 80, p: 0, c: 2, f: 8,  ing: [['Cajun spice', 6, 'g', 'Pantry & Other'], ['Olive oil', 8, 'ml', 'Fats & Oils']], d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'Lemon-herb',    k: 70, p: 0, c: 1, f: 8,  ing: [['Mixed herbs', 5, 'g', 'Pantry & Other'], ['Olive oil', 8, 'ml', 'Fats & Oils']], d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'Peri-peri',     k: 75, p: 0, c: 3, f: 7,  ing: [['Peri-peri sauce', 20, 'g', 'Pantry & Other']], d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'Harissa',       k: 80, p: 0, c: 3, f: 8,  ing: [['Harissa', 20, 'g', 'Pantry & Other'], ['Olive oil', 6, 'ml', 'Fats & Oils']], d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'Garlic-butter', k: 110, p: 0, c: 1, f: 12, ing: [['Butter', 12, 'g', 'Fats & Oils'], ['Garlic', 2, 'clove', 'Vegetables']], d: ['meat', 'vegetarian', 'paleo', 'keto'] },
  { n: 'Teriyaki',      k: 70, p: 1, c: 14, f: 0, ing: [['Teriyaki sauce', 25, 'g', 'Pantry & Other']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'Katsu curry',   k: 120, p: 2, c: 12, f: 7, ing: [['Curry sauce', 60, 'g', 'Pantry & Other']], d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'Salsa & lime',  k: 40, p: 1, c: 6, f: 1,  ing: [['Salsa', 40, 'g', 'Pantry & Other'], ['Lime', 0.5, '', 'Fruits']], d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'Pesto',         k: 120, p: 2, c: 2, f: 12, ing: [['Pesto', 20, 'g', 'Pantry & Other']], d: ['meat', 'vegetarian', 'keto'] },
];

// ── BREAKFAST components ──
const BREK_BASE: Comp[] = [
  { n: 'oats', ico: '🥣', k: 240, p: 8, c: 44, f: 5,  ing: [['Rolled oats', 60, 'g', 'Grains & Bread'], ['Milk', 200, 'ml', 'Dairy & Eggs']], step: 'Cook the oats with milk.', d: ['meat', 'vegetarian'] },
  { n: 'overnight oats', ico: '🥣', k: 250, p: 9, c: 45, f: 6, ing: [['Rolled oats', 60, 'g', 'Grains & Bread'], ['Soy milk', 200, 'ml', 'Dairy & Eggs']], step: 'Soak the oats overnight.', d: ['vegetarian', 'vegan', 'meat'] },
  { n: 'Greek yogurt bowl', ico: '🥣', k: 200, p: 20, c: 14, f: 6, ing: [['Greek yogurt', 200, 'g', 'Dairy & Eggs']], step: 'Spoon the yogurt into a bowl.', d: ['vegetarian', 'meat'] },
  { n: 'omelette', ico: '🍳', k: 230, p: 19, c: 2, f: 16, ing: [['Eggs', 3, '', 'Dairy & Eggs']], step: 'Whisk and cook the eggs into an omelette.', d: ['vegetarian', 'paleo', 'keto', 'meat'] },
  { n: 'tofu scramble', ico: '🍳', k: 190, p: 20, c: 6, f: 10, ing: [['Firm tofu', 150, 'g', 'Pantry & Other'], ['Turmeric', 1, 'pinch', 'Pantry & Other']], step: 'Scramble the tofu with turmeric.', d: ['vegan', 'vegetarian'] },
  { n: 'chia pudding', ico: '🍮', k: 220, p: 8, c: 20, f: 12, ing: [['Chia seeds', 30, 'g', 'Nuts & Seeds'], ['Soy milk', 200, 'ml', 'Dairy & Eggs']], step: 'Set the chia in milk overnight.', d: ['vegan', 'vegetarian', 'keto', 'paleo'] },
  { n: 'protein pancakes', ico: '🥞', k: 280, p: 24, c: 30, f: 6, ing: [['Oat flour', 50, 'g', 'Grains & Bread'], ['Egg', 1, '', 'Dairy & Eggs'], ['Whey protein', 1, 'scoop', 'Pantry & Other']], step: 'Blend and griddle the pancake batter.', d: ['vegetarian', 'meat'] },
  { n: 'cottage cheese bowl', ico: '🥣', k: 180, p: 22, c: 8, f: 6, ing: [['Cottage cheese', 200, 'g', 'Dairy & Eggs']], step: 'Spoon the cottage cheese into a bowl.', d: ['vegetarian', 'meat', 'keto'] },
  { n: 'avocado & eggs', ico: '🥑', k: 320, p: 15, c: 8, f: 26, ing: [['Avocado', 1, '', 'Fruits'], ['Eggs', 2, '', 'Dairy & Eggs']], step: 'Serve sliced avocado with the eggs.', d: ['vegetarian', 'paleo', 'keto', 'meat'] },
  { n: 'shakshuka', ico: '🍳', k: 260, p: 16, c: 12, f: 16, ing: [['Eggs', 2, '', 'Dairy & Eggs'], ['Tomato passata', 150, 'g', 'Pantry & Other']], step: 'Poach the eggs in spiced tomato sauce.', d: ['vegetarian', 'paleo', 'keto', 'meat'] },
];
const BREK_TOP: Comp[] = [
  { n: 'berry',   ing: [['Mixed berries', 80, 'g', 'Fruits']], k: 45, p: 1, c: 10, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'banana',  ing: [['Banana', 1, '', 'Fruits']], k: 90, p: 1, c: 23, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'apple & cinnamon', ing: [['Apple', 1, '', 'Fruits']], k: 80, p: 0, c: 21, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'mango',   ing: [['Mango', 120, 'g', 'Fruits']], k: 80, p: 1, c: 20, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'granola', ing: [['Granola', 40, 'g', 'Grains & Bread']], k: 180, p: 4, c: 28, f: 6, d: ['meat', 'vegetarian', 'vegan'] },
  { n: 'peanut butter', ing: [['Peanut butter', 20, 'g', 'Nuts & Seeds']], k: 120, p: 5, c: 4, f: 10, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'mixed nuts', ing: [['Mixed nuts', 25, 'g', 'Nuts & Seeds']], k: 150, p: 5, c: 5, f: 13, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'honey drizzle', ing: [['Honey', 15, 'g', 'Pantry & Other']], k: 45, p: 0, c: 12, f: 0, d: ['meat', 'vegetarian'] },
];
const BREK_BOOST: Comp[] = [
  { n: '', ing: [], k: 0, p: 0, c: 0, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: '+ protein', ing: [['Whey protein', 1, 'scoop', 'Pantry & Other']], k: 120, p: 24, c: 3, f: 2, d: ['meat', 'vegetarian'] },
  { n: '+ pea protein', ing: [['Pea protein', 1, 'scoop', 'Pantry & Other']], k: 110, p: 22, c: 3, f: 2, d: ['vegan', 'vegetarian'] },
  { n: '+ chia', ing: [['Chia seeds', 15, 'g', 'Nuts & Seeds']], k: 75, p: 3, c: 6, f: 5, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: '+ flaxseed', ing: [['Ground flaxseed', 15, 'g', 'Nuts & Seeds']], k: 80, p: 3, c: 4, f: 6, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: '+ almond butter', ing: [['Almond butter', 15, 'g', 'Nuts & Seeds']], k: 100, p: 3, c: 3, f: 9, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
];
const BREK_STYLE: Comp[] = ([
  { n: '' }, { n: 'warm' }, { n: 'chilled' }, { n: 'with cinnamon' }, { n: 'with vanilla' }, { n: 'with a pinch of sea salt' },
] as { n: string }[]).map((x) => ({ ...x, ing: [] as Ing[], k: 0, p: 0, c: 0, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] as Diet[] }));
const SNACK_PREP: Comp[] = ([
  { n: '' }, { n: 'on the go' }, { n: 'pre-workout' }, { n: 'post-workout' },
] as { n: string }[]).map((x) => ({ ...x, ing: [] as Ing[], k: 0, p: 0, c: 0, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] as Diet[] }));

// ── SNACK components (paired A + B) ──
const SNACK_A: Comp[] = [
  { n: 'Greek yogurt', ico: '🥣', ing: [['Greek yogurt', 150, 'g', 'Dairy & Eggs']], k: 130, p: 15, c: 9, f: 4, d: ['vegetarian', 'meat', 'keto'] },
  { n: 'cottage cheese', ico: '🧀', ing: [['Cottage cheese', 150, 'g', 'Dairy & Eggs']], k: 130, p: 17, c: 6, f: 4, d: ['vegetarian', 'meat', 'keto'] },
  { n: 'protein shake', ico: '🥤', ing: [['Whey protein', 1, 'scoop', 'Pantry & Other'], ['Milk', 200, 'ml', 'Dairy & Eggs']], k: 230, p: 32, c: 14, f: 4, d: ['vegetarian', 'meat'] },
  { n: 'pea-protein shake', ico: '🥤', ing: [['Pea protein', 1, 'scoop', 'Pantry & Other'], ['Soy milk', 200, 'ml', 'Dairy & Eggs']], k: 210, p: 28, c: 14, f: 3, d: ['vegan', 'vegetarian'] },
  { n: 'hummus', ico: '🫓', ing: [['Hummus', 80, 'g', 'Pantry & Other']], k: 180, p: 6, c: 14, f: 11, d: ['vegan', 'vegetarian', 'meat'] },
  { n: 'boiled eggs', ico: '🥚', ing: [['Eggs', 2, '', 'Dairy & Eggs']], k: 140, p: 12, c: 1, f: 10, d: ['vegetarian', 'paleo', 'keto', 'meat'] },
  { n: 'edamame', ico: '🫛', ing: [['Edamame', 120, 'g', 'Vegetables']], k: 120, p: 11, c: 9, f: 5, d: ['vegan', 'vegetarian'] },
  { n: 'beef jerky', ico: '🥩', ing: [['Beef jerky', 40, 'g', 'Meat & Seafood']], k: 120, p: 20, c: 5, f: 2, d: ['meat', 'paleo', 'keto'] },
  { n: 'tuna pot', ico: '🐟', ing: [['Tuna', 80, 'g', 'Meat & Seafood']], k: 110, p: 24, c: 0, f: 1, d: ['meat', 'paleo', 'keto'] },
  { n: 'cheese', ico: '🧀', ing: [['Cheddar', 40, 'g', 'Dairy & Eggs']], k: 160, p: 10, c: 1, f: 13, d: ['vegetarian', 'keto', 'meat'] },
  { n: 'nut-butter toast', ico: '🍞', ing: [['Wholegrain bread', 1, 'slice', 'Grains & Bread'], ['Peanut butter', 15, 'g', 'Nuts & Seeds']], k: 200, p: 8, c: 20, f: 11, d: ['vegan', 'vegetarian', 'meat'] },
  { n: 'oatcakes', ico: '🥯', ing: [['Oatcakes', 3, '', 'Grains & Bread']], k: 130, p: 3, c: 22, f: 4, d: ['vegan', 'vegetarian', 'meat'] },
  { n: 'rice cakes', ico: '🍘', ing: [['Rice cakes', 2, '', 'Grains & Bread']], k: 70, p: 1, c: 15, f: 0, d: ['vegan', 'vegetarian', 'meat'] },
  { n: 'protein bar', ico: '🍫', ing: [['Protein bar', 1, '', 'Pantry & Other']], k: 200, p: 20, c: 20, f: 6, d: ['vegetarian', 'meat'] },
  { n: 'smoothie', ico: '🥤', ing: [['Frozen fruit', 120, 'g', 'Fruits'], ['Yogurt', 100, 'g', 'Dairy & Eggs']], k: 170, p: 8, c: 28, f: 3, d: ['vegetarian', 'meat'] },
  { n: 'olives & cheese', ico: '🫒', ing: [['Olives', 40, 'g', 'Fats & Oils'], ['Feta', 40, 'g', 'Dairy & Eggs']], k: 180, p: 7, c: 2, f: 16, d: ['vegetarian', 'keto', 'meat'] },
  { n: 'avocado', ico: '🥑', ing: [['Avocado', 1, '', 'Fruits']], k: 240, p: 3, c: 12, f: 22, d: ['vegan', 'vegetarian', 'paleo', 'keto', 'meat'] },
  { n: 'salami slices', ico: '🥩', ing: [['Salami', 40, 'g', 'Meat & Seafood']], k: 170, p: 9, c: 1, f: 15, d: ['paleo', 'keto', 'meat'] },
  { n: 'mixed-nut pot', ico: '🥜', ing: [['Mixed nuts', 30, 'g', 'Nuts & Seeds']], k: 180, p: 6, c: 6, f: 15, d: ['vegan', 'vegetarian', 'paleo', 'keto', 'meat'] },
];
const SNACK_B: Comp[] = [
  { n: 'berries', ing: [['Mixed berries', 80, 'g', 'Fruits']], k: 45, p: 1, c: 10, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'apple', ing: [['Apple', 1, '', 'Fruits']], k: 80, p: 0, c: 21, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'banana', ing: [['Banana', 1, '', 'Fruits']], k: 90, p: 1, c: 23, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'orange', ing: [['Orange', 1, '', 'Fruits']], k: 70, p: 1, c: 17, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'pear', ing: [['Pear', 1, '', 'Fruits']], k: 90, p: 1, c: 23, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'grapes', ing: [['Grapes', 100, 'g', 'Fruits']], k: 70, p: 1, c: 18, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'almonds', ing: [['Almonds', 20, 'g', 'Nuts & Seeds']], k: 120, p: 4, c: 4, f: 11, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'walnuts', ing: [['Walnuts', 20, 'g', 'Nuts & Seeds']], k: 130, p: 3, c: 3, f: 13, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'macadamias', ing: [['Macadamias', 20, 'g', 'Nuts & Seeds']], k: 145, p: 2, c: 3, f: 15, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'pumpkin seeds', ing: [['Pumpkin seeds', 20, 'g', 'Nuts & Seeds']], k: 110, p: 6, c: 3, f: 9, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'carrot sticks', ing: [['Carrots', 1, '', 'Vegetables']], k: 35, p: 1, c: 8, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'cucumber & pepper', ing: [['Cucumber', 0.5, '', 'Vegetables'], ['Bell pepper', 0.5, '', 'Vegetables']], k: 30, p: 1, c: 6, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo', 'keto'] },
  { n: 'dark chocolate', ing: [['Dark chocolate', 20, 'g', 'Pantry & Other']], k: 110, p: 1, c: 9, f: 8, d: ['meat', 'vegetarian', 'vegan', 'keto'] },
  { n: 'dates', ing: [['Dates', 3, '', 'Fruits']], k: 120, p: 1, c: 31, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'a piece of fruit', ing: [['Seasonal fruit', 1, '', 'Fruits']], k: 80, p: 1, c: 20, f: 0, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
  { n: 'trail mix', ing: [['Trail mix', 30, 'g', 'Nuts & Seeds']], k: 150, p: 4, c: 14, f: 9, d: ['meat', 'vegetarian', 'vegan', 'paleo'] },
];

export interface GeneratedMeal {
  n: string; slot: Slot; ico: string;
  k: number; p: number; c: number; f: number;
  ing: Ing[]; steps: string[]; diet: Diet; idx: number;
}
export interface PlannedMeal extends GeneratedMeal {
  pos: number; servings: number; K: number; P: number; C: number; F: number;
}

/** Component pools for a given diet + slot (mixed-radix dimensions). */
function dims(diet: Diet, slot: Slot, avoid: Allergen[] = []): Comp[][] {
  const f = (arr: Comp[]) => poolFilter(forDiet(arr, diet), avoid);
  if (slot === 'Breakfast') return [f(BREK_BASE), f(BREK_TOP), f(BREK_BOOST), f(BREK_STYLE)];
  if (slot === 'Snack')     return [f(SNACK_A), f(SNACK_B), f(SNACK_PREP)];
  return [f(PROTEINS), f(CARBS), f(VEGS), f(FLAVORS)];
}

/** Number of distinct meals available for a diet + slot. */
export function catalogSize(diet: Diet, slot: Slot, avoid: Allergen[] = []): number {
  return dims(diet, slot, avoid).reduce((a, p) => a * Math.max(1, p.length), 1);
}

/** Deterministic index → concrete meal (macros, ingredients, method). */
export function mealAt(diet: Diet, slot: Slot, idx: number, avoid: Allergen[] = []): GeneratedMeal {
  const pools = dims(diet, slot, avoid);
  const sizes = pools.map((p) => Math.max(1, p.length));
  const total = sizes.reduce((a, b) => a * b, 1);
  idx = ((idx % total) + total) % total;
  const parts: (Comp | null)[] = [];
  let r = idx;
  for (let i = sizes.length - 1; i >= 0; i--) {
    parts[i] = pools[i].length ? pools[i][r % sizes[i]] : null;
    r = Math.floor(r / sizes[i]);
  }
  const sum = (k: 'k' | 'p' | 'c' | 'f') => parts.reduce((a, p) => a + (p?.[k] ?? 0), 0);
  const ing = parts.flatMap((p) => p?.ing ?? []);
  // ── a dimension with nothing in it ──────────────────────────────────────
  //
  // `parts[i]` is null when a component pool is empty for this diet, and every
  // branch below reads `.n` straight off the tuple — so the whole nutrition
  // screen threw a TypeError out of render. It is reachable: `diet` is a plain
  // text column cast to a five-member union, and a row holding anything else
  // (an older vocabulary, an import, a typo) has no pools at all. That ingress
  // is closed by `readDiet` in src/lib/types.ts; this is the second lock, and
  // it is the one that matters, because a crash inside render takes the tab bar
  // with it.
  //
  // An empty component contributes no name, no icon, no macros and no
  // ingredients — which is exactly what a dimension with nothing in it means —
  // and the sentences below are written to close up around a blank.
  const EMPTY: Comp = { n: '', k: 0, p: 0, c: 0, f: 0, ing: [], d: [] };
  const at = (i: number): Comp => parts[i] ?? EMPTY;
  let n: string, ico: string, steps: string[];
  if (slot === 'Breakfast') {
    const [base, top, boost, style] = [at(0), at(1), at(2), at(3)];
    n = `${cap(top.n)} ${base.n}${boost.n ? ' ' + boost.n : ''}${style.n ? ' — ' + style.n : ''}`;
    ico = base.ico ?? '🍽️';
    steps = [
      base.step ?? `Prepare the ${base.n}.`,
      `Top with ${top.n}${boost.n ? ` and stir in the ${boost.n.replace('+ ', '')}` : ''}.`,
      `Finish${style.n ? ` — ${style.n}` : ' with a pinch of cinnamon or sea salt to taste'}, then serve.`,
    ];
  } else if (slot === 'Snack') {
    const [a, b, prep] = [at(0), at(1), at(2)];
    n = `${cap(a.n)} & ${b.n}${prep.n ? ' (' + prep.n + ')' : ''}`;
    ico = a.ico ?? '🍎';
    steps = [
      `Portion the ${a.n} into a bowl or container.`,
      `Add the ${b.n} alongside${prep.n ? ` — ideal ${prep.n}` : ''}, then enjoy.`,
    ];
  } else {
    const [pr, cb, vg, fl] = [at(0), at(1), at(2), at(3)];
    n = `${fl.n} ${pr.n} with ${cb.n} & ${vg.n}`;
    ico = pr.ico ?? '🍽️';
    const cookTime = /salmon|fish|cod|prawn/i.test(pr.n) ? ' (about 3–4 min per side)' : /chicken|turkey|beef|steak/i.test(pr.n) ? ' (about 5–7 min per side)' : ' until cooked through';
    steps = [
      `Season the ${pr.n} with the ${fl.n.toLowerCase()} flavouring and rest 5 min while you prep.`,
      `Cook the ${cb.n} until tender (per pack if applicable) and keep warm.`,
      `Cook the ${pr.n} over medium-high heat${cookTime}.`,
      `Meanwhile, steam or sauté the ${vg.n} for 3–4 min until bright and just tender.`,
      `Plate the ${cb.n}, top with the ${pr.n} and ${vg.n}, spoon over any pan juices, and serve.`,
    ];
  }
  return { n, slot, ico, k: sum('k'), p: sum('p'), c: sum('c'), f: sum('f'), ing, steps, diet, idx };
}

// ── Client shape the planner needs (subset of the full client) ──
export interface PlanInput extends BodyStats {
  id: string;
  weightKg: number;          // latest weight (also used to seed)
  mealsPerDay: 3 | 4 | 5;
  mealOverride?: Record<number, number>;
  coachAdjust?: CoachAdjust;
  avoid?: Allergen[];
  /**
   * The goal-date energy plan, when the member has a target weight and a date.
   *
   * Declared here rather than only reaching `macrosFor` through the structural
   * type: `buildPlan` hands its whole input straight to it, so this field
   * decides the calorie figure the meals below are scaled to. It was already
   * being passed by app/(client)/nutrition.tsx and was invisible on this
   * interface, which is how the Food Log came to compute the same day without
   * it. See src/lib/dayTarget.ts.
   */
  energyPlan?: EnergyPlan | null;
}

export function slotsFor(mealsPerDay: number): Slot[] {
  return mealsPerDay >= 5 ? ['Breakfast', 'Snack', 'Lunch', 'Snack', 'Dinner']
    : mealsPerDay === 4 ? ['Breakfast', 'Lunch', 'Snack', 'Dinner']
    : ['Breakfast', 'Lunch', 'Dinner'];
}

/** Stable per-slot seed so a client's default plan is reproducible. */
function mealSeed(c: PlanInput, slotIdx: number): number {
  return (c.id.charCodeAt(1) || 0) + Math.round(c.weightKg) * 3 + slotIdx * 7;
}

/** Build a day's plan scaled toward the client's calorie target. */
export function buildPlan(c: PlanInput): { plan: PlannedMeal[]; target: ReturnType<typeof macrosFor>; tot: { K: number; P: number; C: number; F: number } } {
  const target = applyCoachAdjust(macrosFor(c), c.coachAdjust);
  const slots = slotsFor(c.mealsPerDay);
  const override = c.mealOverride ?? {};
  const avoid = c.avoid ?? [];
  let plan: PlannedMeal[] = slots.map((slot, i) => {
    const size = catalogSize(c.diet, slot, avoid);
    const idx = (override[i] != null ? override[i] : mealSeed(c, i)) % size;
    const meal = mealAt(c.diet, slot, idx, avoid);
    return { ...meal, pos: i, servings: 1, K: meal.k, P: meal.p, C: meal.c, F: meal.f };
  });
  const base = plan.reduce((a, x) => a + x.k, 0) || 1;
  const scale = target.kcal / base;
  plan = plan.map((x) => {
    const s = Math.max(0.5, Math.round(scale * 4) / 4);
    return { ...x, servings: s, K: Math.round(x.k * s), P: Math.round(x.p * s), C: Math.round(x.c * s), F: Math.round(x.f * s) };
  });
  const tot = {
    K: plan.reduce((a, x) => a + x.K, 0), P: plan.reduce((a, x) => a + x.P, 0),
    C: plan.reduce((a, x) => a + x.C, 0), F: plan.reduce((a, x) => a + x.F, 0),
  };
  return { plan, target, tot };
}

/**
 * Snack ideas, whatever the plan is built from.
 *
 * The snack catalogue has always existed, and until now the only way to reach
 * it was to notice a small "Meals per day 3 4 5" row inside the plan and
 * change 3 to 4 — which rebuilds the whole day's meals as a side effect of
 * wanting an apple and some almonds. Reported simply as: the meals section
 * needs snacks.
 *
 * So these are ideas rather than plan slots. They do not move the day's
 * targets or the macro split, because a snack somebody has not eaten yet is
 * not a commitment; logging one is what counts it, the same as any other food.
 * A client whose plan already carries Snack slots still gets them — more ideas
 * is not a contradiction, and the section says which is which.
 *
 * Portioned to roughly an eighth of the day rather than a meal's share: the
 * plan scales its meals to fill the target, and a snack scaled the same way is
 * a fourth meal.
 */
export function snackIdeas(c: PlanInput, count = 3): PlannedMeal[] {
  const avoid = c.avoid ?? [];
  const size = catalogSize(c.diet, 'Snack', avoid);
  if (!size) return [];
  const target = applyCoachAdjust(macrosFor(c), c.coachAdjust);
  const want = target.kcal * SNACK_SHARE;
  // Seeded off the client like the plan is, and stepped by a number coprime
  // with nothing in particular — the point is only that the three ideas are
  // stable for a given client and are not three variations of one thing.
  const seed = mealSeed(c, SNACK_SEED_SLOT);
  const out: PlannedMeal[] = [];
  for (let i = 0; i < Math.min(count, size); i++) {
    const meal = mealAt(c.diet, 'Snack', (seed + i * 37) % size, avoid);
    const servings = Math.max(0.5, Math.round((want / Math.max(1, meal.k)) * 4) / 4);
    out.push({
      ...meal,
      // Negative, so a snack idea can never collide with a plan slot in the
      // override map or in a React key.
      pos: -1 - i,
      servings,
      K: Math.round(meal.k * servings), P: Math.round(meal.p * servings),
      C: Math.round(meal.c * servings), F: Math.round(meal.f * servings),
    });
  }
  return out;
}

/** A snack is about an eighth of the day. */
export const SNACK_SHARE = 0.125;
/** A slot index no real plan uses, so snack seeds never track a meal's. */
const SNACK_SEED_SLOT = 97;

/** Next meal in the catalog for a slot (the "swap" action). */
export function swapIndex(diet: Diet, slot: Slot, currentIdx: number, avoid: Allergen[] = []): number {
  return (currentIdx + 1) % catalogSize(diet, slot, avoid);
}

/** Search a slot's catalog by name (used by the "choose a meal" picker). */
export function searchMeals(diet: Diet, slot: Slot, query: string, limit = 40, avoid: Allergen[] = []): GeneratedMeal[] {
  const size = catalogSize(diet, slot, avoid);
  const scan = Math.min(size, 800);
  const q = (query || '').toLowerCase();
  const rows: GeneratedMeal[] = [];
  for (let i = 0; i < scan && rows.length < limit; i++) {
    const m = mealAt(diet, slot, i, avoid);
    if (!q || m.n.toLowerCase().includes(q)) rows.push(m);
  }
  return rows;
}

// ── Weekly grocery list ──────────────────────────────────────────────────────
/** How many days a plan week and its grocery list cover. */
export const PLAN_WEEK_DAYS = 7;

/**
 * THE WEEK THE MEMBER IS SHOWN — one function, so the list they shop from is
 * for the meals they are looking at.
 *
 * ── What was wrong ────────────────────────────────────────────────────────
 *
 * There were two weeks. The screen drew one (`app/(client)/nutrition.tsx`,
 * week view): the coach's written day where there is one, otherwise today's
 * plan stepped along the catalogue, `idx + d`. The grocery list was built from
 * a `planForDay` that read neither — it re-seeded from scratch with
 * `mealSeed(c, i) + dayOffset * 17 + i * 3` and never looked at
 * `c.mealOverride` at all.
 *
 * So "Grocery List · N items" bought ingredients for meals the member had
 * already swapped away from, and for a week that was not the coach-written one
 * printed directly above it. Not a rounding difference — a different week.
 *
 * `coachDay` is how the caller supplies the coach's written days without this
 * file having to know about src/lib/mealPlan.ts, which imports this one. Return
 * null for a day the coach has not written and the synthetic step is used, day
 * by day, exactly as the screen draws it.
 */
export function planWeek(
  c: PlanInput,
  coachDay?: (d: number) => Record<number, number> | null,
): PlannedMeal[][] {
  // Day zero of the synthetic week is the plan as it stands, overrides and
  // swaps included — `idx + d` steps from what is on screen rather than from a
  // seed nobody can see.
  const today = buildPlan(c).plan;
  const out: PlannedMeal[][] = [];
  for (let d = 0; d < PLAN_WEEK_DAYS; d++) {
    const written = coachDay ? coachDay(d) : null;
    if (written) { out.push(buildPlan({ ...c, mealOverride: written }).plan); continue; }
    const ov: Record<number, number> = {};
    today.forEach((m) => { ov[m.pos] = m.idx + d; });
    out.push(buildPlan({ ...c, mealOverride: ov }).plan);
  }
  return out;
}

export interface GroceryItem { item: string; qty: number; unit: string; }
export interface GroceryData { byDept: Partial<Record<Dept, GroceryItem[]>>; mealCount: number; }

/** Aggregate an already-built week into a department-grouped shopping list. */
export function groceryFromWeek(week: readonly (readonly PlannedMeal[])[]): GroceryData {
  const agg: Record<string, number> = {};
  const meals = new Set<string>();
  for (const day of week) {
    for (const meal of day) {
      meals.add(meal.n);
      meal.ing.forEach(([item, qty, unit, dept]) => {
        const key = `${dept}||${item}||${unit}`;
        agg[key] = (agg[key] || 0) + qty * meal.servings;
      });
    }
  }
  const byDept: Partial<Record<Dept, GroceryItem[]>> = {};
  Object.entries(agg).forEach(([key, q]) => {
    const [dept, item, unit] = key.split('||') as [Dept, string, string];
    let qty: number;
    if (unit === 'g' || unit === 'ml') qty = Math.round(q / 10) * 10;
    else if (['', 'piece', 'slice', 'clove', 'rasher', 'scoop', 'cup', 'pinch'].includes(unit)) qty = Math.ceil(q);
    else qty = Math.round(q * 10) / 10;
    (byDept[dept] = byDept[dept] || []).push({ item, qty, unit });
  });
  (Object.values(byDept) as GroceryItem[][]).forEach((list) => list.sort((a, b) => a.item.localeCompare(b.item)));
  return { byDept, mealCount: meals.size };
}

/** The shopping list for the week this client is shown. */
export function groceryData(c: PlanInput, coachDay?: (d: number) => Record<number, number> | null): GroceryData {
  return groceryFromWeek(planWeek(c, coachDay));
}
