/** The Live Activity target — the workout clock on the lock screen.
 *
 *  A widget extension, declared here rather than in Xcode, because `ios/` is
 *  gitignored and regenerated by prebuild: anything added to the generated
 *  project by hand is deleted the next time somebody runs it. This file is the
 *  version of that target which survives.
 *
 *  `@bacons/apple-targets` owns the .pbxproj surgery. Hand-editing a project
 *  file to add an extension target is the part of this that goes wrong quietly,
 *  and it is not work worth owning here.
 */
module.exports = {
  type: 'widget',
  name: 'WorkoutActivity',
  // The Live Activity is driven entirely from the phone — start, tick, end —
  // so there is no push entitlement here and no APNs key to keep alive.
  // ActivityKit updates a running Activity locally, and the clock below is a
  // SwiftUI timer over a date, so it counts without anything waking the app.
  entitlements: {},
};
