-- ─────────────────────────────────────────────────────────────────────────
-- A coach can put an item on one client's daily checklist.
--
-- TF-31: "What generates the daily checklist? Is it actually useful?" It was
-- generated by a five-element array literal in src/ui/habits.tsx — the same
-- "10,000 steps" and "Sleep 7h+" for every account on the platform, and no way
-- for anybody to add, remove or change a line. The product owner's answer was
-- that it should come "from your plan and targets — as well as the ones set by
-- the coach". The plan and targets the app already holds; this table is the
-- half that had nowhere to live.
--
-- Additive only. Nothing here alters an existing table, and every statement is
-- guarded so the file is safe to re-run.
--
-- ── Why a row per item, and not jsonb on one row per client ─────────────────
--
-- `assigned_programs` and `coach_nutrition` both take the other shape — one row
-- per client, the payload in a column — and either would have been less work
-- here. They are the wrong shape for this, for one reason: a tick is a row in
-- `habit_logs` keyed (user_id, habit, done_on), and `habit` is a TEXT id the
-- client's app sends. Inside a jsonb array the only identifier an item has is
-- its position, so a coach reordering their list on Tuesday would silently
-- reattach Monday's ticks to different items, and a coach who deleted the first
-- of five would shift four days of history by one. A uuid primary key is an
-- identifier that survives both, and survives a rename as well: the client's
-- app keys the habit on 'coach:' || id (see COACH_ID_PREFIX in
-- src/lib/checklist.ts), so a coach fixing a typo does not cost the client
-- their streak.
--
-- ── Why `active` rather than deleting the row ──────────────────────────────
--
-- A coach taking an item off the list should not take the record of it with
-- them. The client's ticks stay in `habit_logs` either way — nothing here
-- cascades to them — but with the row gone, neither app can say what
-- 'coach:8f3e…' in that history meant. Deactivating keeps last month's ticks
-- legible. A coach who genuinely wants the row gone can still delete it; the
-- app's own remove path sets `active` to false.
--
-- ── What this table is NOT ─────────────────────────────────────────────────
--
-- It is not a place for the coach to record whether the client did the thing.
-- There is no `done` column and there must not be one: the tick belongs to the
-- client, in `habit_logs`, where the client's own policy governs it. A coach
-- column saying "done" would be a second answer to a question only one person
-- can answer.
--
-- ── A correction to the sentence that used to end that paragraph ───────────
--
-- It read "and the coach dashboard already reads the client's real ticks". No
-- such reader existed. `habit_logs_coach_read` in 02-domain-schema.sql has
-- granted it all along — `for select using (is_my_client(user_id))` — and not
-- one query in either app or the console used the grant, so an item went onto
-- a client's list and nothing on the coach's side could say whether any of it
-- was ever done. The decision above stands on its own and did not need the
-- reassurance; what the reassurance did was describe a screen that was not
-- there, which is the most expensive shape a comment can take, because it is
-- the reason nobody went looking for the gap. The read exists now, on the
-- coach's checklist screen in the phone app: it reads `habit_logs` over a
-- four-week window and states only what those rows can support
-- (app/(trainer)/checklists.tsx, and src/lib/adherence.ts for the arithmetic
-- and for the several things it deliberately refuses to say). The console's
-- editor at /coach/checklists has not caught up yet.
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.coach_checklist_items (
  id uuid primary key default gen_random_uuid(),

  -- Cascade on both sides, matching coach_feedback. A checklist item is a thing
  -- one person set for another; with either of them deleted it is not a row
  -- anybody can read, act on or account for.
  client_id uuid not null references public.profiles(id) on delete cascade,
  coach_id  uuid not null references public.profiles(id) on delete cascade,

  -- What the client reads on the line. Bounded because it is rendered on one
  -- row of a phone screen, and non-empty because an unlabelled circle to tick
  -- is worse than no line at all — the app drops blank labels too, but the
  -- constraint is what stops one being stored in the first place.
  label text not null check (btrim(label) <> '' and length(label) <= 80),

  -- One emoji, optional. Empty means "the app picks", not "no icon" — the
  -- client's app substitutes its own so a line never renders short.
  icon text not null default '' check (length(icon) <= 8),

  -- Off, not gone. See the header.
  active boolean not null default true,

  -- The coach's own ordering. Ties break on created_at so a list where nobody
  -- has set an order is still stable between reads rather than shuffling.
  sort int not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Nobody coaches themselves, and a self-row would satisfy the client policy
  -- and the coach policy at once — which is a way around the relationship check
  -- below rather than a use case.
  constraint coach_checklist_items_not_self check (coach_id <> client_id)
);

-- The client's app reads this list on every launch, filtered to their own
-- active rows and ordered. This is that query.
create index if not exists idx_coach_checklist_client
  on public.coach_checklist_items (client_id, active, sort, created_at);

-- The coach's app reads their own list for one client.
create index if not exists idx_coach_checklist_coach
  on public.coach_checklist_items (coach_id, client_id);

comment on table public.coach_checklist_items is
  'Daily-checklist items a coach set for one client. The client''s ticks live in habit_logs under the id ''coach:'' || id.';

alter table public.coach_checklist_items enable row level security;

-- ── The client reads their own, and nothing else ───────────────────────────
--
-- SELECT only. A client who could edit these could quietly delete the item they
-- keep missing, and their coach would have no way to tell that from a coach who
-- never set it — which is the same class of bug as the one TF-31 is about.
-- Removing an item is a conversation with the coach, not a swipe.
--
-- Inactive rows come back too. The client's app filters them out; the policy
-- does not, because a client's own history is the one thing they are always
-- entitled to read, and a coach deactivating an item is not a reason to hide
-- what they were asked to do last month.
drop policy if exists coach_checklist_client_read on public.coach_checklist_items;
create policy coach_checklist_client_read on public.coach_checklist_items for select
  using (client_id = auth.uid());

-- ── The coach writes, for the clients they actually coach ──────────────────
--
-- `is_my_client` (02-domain-schema.sql) is the same predicate that already
-- governs every coach read of a client's domain data — workouts, measurements,
-- check_ins and habit_logs all hang off it — so a coach who can see a client's
-- ticks is exactly the coach who can add to the list those ticks are against.
-- Using it here rather than a second hand-written EXISTS is deliberate: two
-- spellings of "my client" that can drift apart is how a coach ends up able to
-- write a row they cannot then read.
--
-- `coach_id = auth.uid()` in the CHECK is what stops a coach setting an item in
-- somebody else's name. It is in the USING clause as well, so a coach cannot
-- edit or deactivate an item a colleague set for a client they share.
drop policy if exists coach_checklist_coach_write on public.coach_checklist_items;
create policy coach_checklist_coach_write on public.coach_checklist_items for all
  using      (coach_id = auth.uid() and public.is_my_client(client_id))
  with check (coach_id = auth.uid() and public.is_my_client(client_id));

-- ── updated_at ──────────────────────────────────────────────────────────────
--
-- Stamped here rather than trusted from the client, because "when did my coach
-- last change my list" is the sort of thing an app will eventually show and a
-- value the writer supplies is a value the writer can get wrong.
create or replace function public.touch_coach_checklist_item()
returns trigger language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists touch_coach_checklist_item_t on public.coach_checklist_items;
create trigger touch_coach_checklist_item_t
  before update on public.coach_checklist_items
  for each row execute function public.touch_coach_checklist_item();

-- Trigger functions are reachable by nobody; see 51-advisor-tidy.sql.
revoke execute on function public.touch_coach_checklist_item() from public, anon, authenticated;
