-- ─────────────────────────────────────────────────────────────────────────
-- The catalogue in German: 583 of 604 movements.
--
-- Part 790 built the table and argued the shape. This is the German content
-- for it, and the only interesting decisions here are about words.
--
-- ── Why this says 604 and not 619 ─────────────────────────────────────────
--
-- It was written on 2 Sep against the 619-row catalogue that parts 49/71/74/
-- 75/76 build on an empty database, and it carried 599 rows. That catalogue is
-- not the one that exists. Part 2260, written two days later, collapses the
-- fifteen movements the regenerated part 74 had split in two — 'bench-press'
-- and 'barbell-bench-press' are one movement, and ours is the row every screen
-- resolves to, because src/lib/machines.ts, src/lib/focus.ts and buildProgram()
-- emit our NAME. Production never had the fifteen at all.
--
-- So sixteen rows here named an exercise_id that production does not hold, and
-- exercise_id is a foreign key. Applying this file to production aborted on the
-- first of them and took the rest of the language with it. The sixteen are gone
-- from the VALUES below:
--
--   · Fifteen were DUPLICATES under a second id. Every one of them has a
--     surviving partner in this file already carrying the right German for the
--     name that survives — 'bench-press' is Bankdrücken, and the deleted row
--     said Langhantel-Bankdrücken for a row whose name is "Bench Press".
--     Nothing was lost; a second answer was removed.
--
--     barbell-back-squat, barbell-bench-press, barbell-deadlift,
--     barbell-hip-thrust, barbell-overhead-press, bent-over-barbell-row,
--     cable-face-pull, cable-glute-kickback, cable-tricep-pushdown,
--     dumbbell-bicep-curl, dumbbell-hammer-curl, dumbbell-lateral-raise,
--     lying-leg-curl, machine-chest-press, machine-hip-abduction.
--
--     Fourteen of the fifteen partners were already translated. The exception
--     is 'cable-kickback', whose partner row was 'cable-glute-kickback': it now
--     has no German, which is the right answer and not an oversight — Cable
--     Kickback is in the list of twenty below, for exactly the reason given
--     there.
--
--   · The sixteenth, 'stability-ball-leg-curl', is NOT a duplicate. It is one
--     movement under two vendor names: RepDB renamed it between the generation
--     production seeded ('ball-leg-curl', "Ball Leg Curl") and the one a fresh
--     database seeds. Neither id is correct on both databases, so no literal
--     row here can name it. Part 2310 writes that one by looking the movement
--     up rather than naming it, and runs after part 2260 so the catalogue is
--     settled by the time it does.
--
-- ── These are gym words, not dictionary words ─────────────────────────────
--
-- A movement name is an instruction. Somebody reads it, walks to a rack and
-- does what it says under load, so the test applied to every line below is
-- "would a lifter in a German gym call it this", never "is this a correct
-- rendering of the English". The two come apart constantly:
--
--   · Bench Press is Bankdrücken, not "Bankpresse".
--   · An EZ-bar is an SZ-Stange. Rendered literally it is nothing.
--   · A Smith machine is a Multipresse. "Schmidt-Maschine" would send
--     somebody looking for a machine that does not exist.
--   · A Preacher Curl is a Scottcurl — named after Larry Scott, and there is
--     no German word for "preacher" that gets anywhere near it.
--   · A Pec Deck is a Butterfly. Every German gym labels the machine that.
--   · A Skull Crusher is Stirndrücken. The literal rendering is unusable.
--   · A Clean is Umsetzen and a Snatch is Reißen — the words used on a
--     German platform, not the words a dictionary offers for the nouns.
--
-- ── Where the German name IS the English one ──────────────────────────────
--
-- Face Pull, Burpees, Hip Thrust, Push Press, Planche, Thruster and a few
-- dozen more are simply what German lifters say, and each of those has a row
-- here carrying the English string. That is deliberate and it is not the same
-- thing as no row: a row is a POSITIVE claim that this is the German name, so
-- the app shows it plainly. No row means nobody has decided, and the app then
-- shows English and says out loud that it is English. Conflating the two would
-- have put an "EN" marker beside "Burpees" forever.
--
-- ── The 20 that stay English, on purpose ──────────────────────────────────
--
-- Ball Pike, Cable Kickback, Chin Tuck Hold, Cocoons, Crab Dips, the three
-- Kickstand Deadlifts, Double Kettlebell Dead Clean / Dead Split Snatch /
-- Swing Snatch, Downward Dog to Knee Drive, Dumbbell Bench Pull, Dumbbell
-- Somersault Squat, Hanging Pike, Kettlebell Lunge Press, Kettlebell Offset
-- Reverse Lunge and Press, One Arm Kettlebell Floor Glute Bridge Press,
-- Standing Side Bend Flow and Thread the Needle Flow.
--
-- Not an oversight and not a to-do. For each of them either the English name
-- is itself ambiguous about what the movement is (Cable Kickback is a glute
-- kickback on some machines and a triceps one on others) or there is no
-- settled German term and inventing one would be guessing. A guessed movement
-- name in a programme is a person doing the wrong exercise under load, and the
-- fallback — English, marked as English — costs nothing but a badge.
--
-- ── Re-running this file ──────────────────────────────────────────────────
--
-- The primary key is (exercise_id, locale) and the conflict clause updates, so
-- running this twice leaves 583 rows and running a corrected copy replaces the
-- names it changes. Nothing is deleted: a row this file no longer carries
-- stays until somebody removes it deliberately, because a name silently
-- vanishing from a language is the failure that looks like nothing happened.
--
-- That last rule is why the sixteen removed above are only removed from THIS
-- file. On a database that already ran the 599-row version they are still
-- present, and part 790's foreign key clears them on its own: they are children
-- of exercises part 2260 deletes, `on delete cascade`. On production, which
-- never held those fifteen exercises, they were never inserted in the first
-- place.
--
-- Descriptions are NOT translated here. `exercises.description` is one
-- sentence per movement across 601 rows, translating it is a separate and much
-- larger judgement call, and part 790's read path already handles a translated
-- name beside an untranslated description — it says so on screen rather than
-- letting the two blur.
-- ─────────────────────────────────────────────────────────────────────────

insert into public.exercise_translations (exercise_id, locale, name) values
  ('ab-crunch', 'de', 'Bauchcrunch'),
  ('ab-wheel-rollout', 'de', 'Bauchroller-Rollout'),
  ('air-bike', 'de', 'Air Bike'),
  ('archer-pull-ups', 'de', 'Archer-Klimmzüge'),
  ('archer-push-ups', 'de', 'Archer-Liegestütze'),
  ('arnold-press', 'de', 'Arnold-Drücken'),
  ('assisted-pull-up', 'de', 'Klimmzug mit Unterstützung'),
  ('back-extension', 'de', 'Rückenstrecken'),
  ('back-lever', 'de', 'Back Lever'),
  ('back-squat', 'de', 'Kniebeuge'),
  ('band-assisted-pull-ups', 'de', 'Klimmzüge mit Band'),
  ('band-pull-apart', 'de', 'Band Pull-Apart'),
  ('banded-adductor-stretch', 'de', 'Adduktorendehnung mit Band'),
  ('banded-ankle-stretch', 'de', 'Sprunggelenkdehnung mit Band'),
  ('banded-calf-stretch', 'de', 'Wadendehnung mit Band'),
  ('banded-chest-stretch', 'de', 'Brustdehnung mit Band'),
  ('banded-clamshell', 'de', 'Clamshell mit Band'),
  ('banded-figure-4-stretch', 'de', 'Figure-4-Dehnung mit Band'),
  ('banded-fire-hydrant', 'de', 'Hüftabduktion im Vierfüßlerstand mit Band'),
  ('banded-glute-bridge', 'de', 'Beckenheben mit Band'),
  ('banded-good-morning', 'de', 'Good Morning mit Band'),
  ('banded-hamstring-stretch', 'de', 'Beinbeugerdehnung mit Band'),
  ('banded-hip-thrust', 'de', 'Hip Thrust mit Band'),
  ('banded-it-band-stretch', 'de', 'IT-Band-Dehnung mit Band'),
  ('banded-kneeling-hip-thrust', 'de', 'Kniender Hip Thrust mit Band'),
  ('banded-lat-stretch', 'de', 'Latissimusdehnung mit Band'),
  ('banded-lateral-walk', 'de', 'Seitwärtsgehen mit Band'),
  ('banded-rear-delt-stretch', 'de', 'Dehnung der hinteren Schulter mit Band'),
  ('banded-romanian-deadlift', 'de', 'Rumänisches Kreuzheben mit Band'),
  ('banded-seated-hip-abduction', 'de', 'Sitzende Hüftabduktion mit Band'),
  ('banded-shoulder-stretch', 'de', 'Schulterdehnung mit Band'),
  ('banded-squat', 'de', 'Kniebeuge mit Band'),
  ('banded-standing-hip-abduction', 'de', 'Stehende Hüftabduktion mit Band'),
  ('banded-standing-hip-adduction', 'de', 'Stehende Hüftadduktion mit Band'),
  ('banded-standing-leg-curl', 'de', 'Stehender Beinbeuger mit Band'),
  ('banded-sumo-walk', 'de', 'Sumo-Gehen mit Band'),
  ('banded-terminal-knee-extension', 'de', 'Terminale Kniestreckung mit Band'),
  ('banded-triceps-stretch', 'de', 'Trizepsdehnung mit Band'),
  ('barbell-ab-rollout', 'de', 'Rollout mit der Langhantel'),
  ('barbell-calf-raise', 'de', 'Wadenheben mit der Langhantel'),
  ('barbell-curl', 'de', 'Langhantelcurl'),
  ('barbell-front-raise', 'de', 'Frontheben mit der Langhantel'),
  ('barbell-glute-bridge', 'de', 'Beckenheben mit der Langhantel'),
  ('barbell-lunge', 'de', 'Ausfallschritt mit der Langhantel'),
  ('barbell-overhead-extension', 'de', 'Überkopf-Trizepsstrecken mit der Langhantel'),
  ('barbell-preacher-curl', 'de', 'Scottcurl mit der Langhantel'),
  ('barbell-pullover', 'de', 'Langhantel-Überzüge'),
  ('barbell-rear-delt-row', 'de', 'Rudern für die hintere Schulter mit der Langhantel'),
  ('barbell-reverse-lunge', 'de', 'Rückwärtiger Ausfallschritt mit der Langhantel'),
  ('barbell-shrug', 'de', 'Schulterheben mit der Langhantel'),
  ('barbell-upright-row', 'de', 'Aufrechtes Rudern mit der Langhantel'),
  ('barbell-wrist-curl', 'de', 'Handgelenkcurl mit der Langhantel'),
  ('battle-rope-double-slam', 'de', 'Battle-Rope-Doppelschlag'),
  ('battle-ropes', 'de', 'Battle Ropes'),
  ('bear-crawl', 'de', 'Bärengang'),
  ('behind-the-back-barbell-shrug', 'de', 'Schulterheben mit der Langhantel hinter dem Rücken'),
  ('behind-the-neck-lat-pulldown', 'de', 'Latzug in den Nacken'),
  ('behind-the-neck-press', 'de', 'Nackendrücken'),
  ('behind-the-neck-pull-up', 'de', 'Klimmzug in den Nacken'),
  ('bench-adductor-stretch', 'de', 'Adduktorendehnung an der Bank'),
  ('bench-ankle-stretch', 'de', 'Sprunggelenkdehnung an der Bank'),
  ('bench-bulgarian-split-stretch', 'de', 'Bulgarische Split-Dehnung an der Bank'),
  ('bench-calf-stretch', 'de', 'Wadendehnung an der Bank'),
  ('bench-chest-stretch', 'de', 'Brustdehnung an der Bank'),
  ('bench-child-s-pose', 'de', 'Kindhaltung an der Bank'),
  ('bench-couch-stretch', 'de', 'Couch-Stretch an der Bank'),
  ('bench-dips', 'de', 'Bankdips'),
  ('bench-figure-4-glute-stretch', 'de', 'Figure-4-Gesäßdehnung an der Bank'),
  ('bench-hamstring-stretch', 'de', 'Beinbeugerdehnung an der Bank'),
  ('bench-lat-stretch', 'de', 'Latissimusdehnung an der Bank'),
  ('bench-leg-pull-in', 'de', 'Knieanziehen auf der Bank'),
  ('bench-press', 'de', 'Bankdrücken'),
  ('bench-pull', 'de', 'Rudern in Bauchlage auf der Bank'),
  ('bent-arm-barbell-pullover', 'de', 'Überzüge mit gebeugten Armen mit der Langhantel'),
  ('bent-arm-ez-bar-pullover', 'de', 'Überzüge mit gebeugten Armen mit der SZ-Stange'),
  ('bent-over-dumbbell-row', 'de', 'Vorgebeugtes Kurzhantelrudern'),
  ('bent-over-ez-bar-row', 'de', 'Vorgebeugtes Rudern mit der SZ-Stange'),
  ('bent-over-row', 'de', 'Vorgebeugtes Rudern'),
  ('bicep-curl', 'de', 'Bizepscurl'),
  ('bicycle-crunch', 'de', 'Fahrrad-Crunch'),
  ('bilateral-dumbbell-wrist-curl', 'de', 'Beidarmiger Handgelenkcurl mit Kurzhanteln'),
  ('bird-dog', 'de', 'Bird-Dog'),
  ('bird-dog-hold', 'de', 'Bird-Dog halten'),
  ('boat-pose', 'de', 'Bootshaltung'),
  ('bodyweight-calf-raise', 'de', 'Wadenheben mit dem eigenen Körpergewicht'),
  ('bodyweight-good-morning', 'de', 'Good Morning ohne Gewicht'),
  ('bodyweight-lateral-raise', 'de', 'Seitheben ohne Gewicht'),
  ('bodyweight-overhead-press', 'de', 'Überkopfdrücken ohne Gewicht'),
  ('bodyweight-reverse-lunge', 'de', 'Rückwärtiger Ausfallschritt ohne Gewicht'),
  ('bodyweight-squat', 'de', 'Kniebeuge ohne Gewicht'),
  ('bow-pose', 'de', 'Bogenhaltung'),
  ('box-jump', 'de', 'Sprung auf die Box'),
  ('box-squat', 'de', 'Box-Kniebeuge'),
  ('bulgarian-split-squat', 'de', 'Bulgarische Kniebeuge'),
  ('burpees', 'de', 'Burpees'),
  ('butterfly-stretch', 'de', 'Schmetterlingsdehnung'),
  ('cable-bent-over-row', 'de', 'Vorgebeugtes Rudern am Kabelzug'),
  ('cable-chest-press', 'de', 'Brustdrücken am Kabelzug'),
  ('cable-crossover', 'de', 'Fliegende am Kabelzug'),
  ('cable-crunch', 'de', 'Crunch am Kabelzug'),
  ('cable-curl', 'de', 'Bizepscurl am Kabelzug'),
  ('cable-external-rotation', 'de', 'Außenrotation am Kabelzug'),
  ('cable-front-raise', 'de', 'Frontheben am Kabelzug'),
  ('cable-hammer-curl', 'de', 'Hammercurl am Kabelzug'),
  ('cable-lateral-raise', 'de', 'Seitheben am Kabelzug'),
  ('cable-machine', 'de', 'Kabelzug'),
  ('cable-pallof-press', 'de', 'Pallof Press am Kabelzug'),
  ('cable-tricep-kickback', 'de', 'Trizeps-Kickback am Kabelzug'),
  ('cable-upright-row', 'de', 'Aufrechtes Rudern am Kabelzug'),
  ('cable-wrist-curl', 'de', 'Handgelenkcurl am Kabelzug'),
  ('calf-raise', 'de', 'Wadenheben'),
  ('camel-pose', 'de', 'Kamelhaltung'),
  ('captain-s-chair-knee-raise', 'de', 'Knieheben im Beinhebestuhl'),
  ('captain-s-chair-leg-raise', 'de', 'Beinheben im Beinhebestuhl'),
  ('cat-cow', 'de', 'Katze-Kuh'),
  ('cat-stretch', 'de', 'Katzendehnung'),
  ('chair-pose', 'de', 'Stuhlhaltung'),
  ('cheat-curl', 'de', 'Cheat Curl'),
  ('chest-dips', 'de', 'Dips für die Brust'),
  ('chest-press', 'de', 'Brustdrücken'),
  ('chest-supported-dumbbell-row', 'de', 'Kurzhantelrudern mit Brustauflage'),
  ('chest-supported-dumbbell-shrug', 'de', 'Schulterheben mit Kurzhanteln und Brustauflage'),
  ('chest-supported-kettlebell-row', 'de', 'Kettlebell-Rudern mit Brustauflage'),
  ('chest-supported-smith-machine-row', 'de', 'Rudern an der Multipresse mit Brustauflage'),
  ('child-s-pose', 'de', 'Kindhaltung'),
  ('chin-ups', 'de', 'Klimmzüge im Untergriff'),
  ('clamshell-hold', 'de', 'Clamshell halten'),
  ('clamshells', 'de', 'Clamshells'),
  ('clap-push-ups', 'de', 'Klatsch-Liegestütze'),
  ('clean', 'de', 'Umsetzen'),
  ('clean-and-jerk', 'de', 'Umsetzen und Stoßen'),
  ('close-grip-barbell-curl', 'de', 'Langhantelcurl im engen Griff'),
  ('close-grip-bench-press', 'de', 'Enges Bankdrücken'),
  ('close-grip-dumbbell-bench-press', 'de', 'Enges Bankdrücken mit Kurzhanteln'),
  ('close-grip-ez-bar-bench-press', 'de', 'Enges Bankdrücken mit der SZ-Stange'),
  ('close-grip-ez-bar-curl', 'de', 'SZ-Curl im engen Griff'),
  ('close-grip-incline-bench-press', 'de', 'Enges Schrägbankdrücken'),
  ('close-grip-lat-pulldown', 'de', 'Latzug im engen Griff'),
  ('close-grip-pull-ups', 'de', 'Klimmzüge im engen Griff'),
  ('close-grip-push-ups', 'de', 'Enge Liegestütze'),
  ('close-stance-leg-press', 'de', 'Beinpresse mit engem Stand'),
  ('cobra-stretch', 'de', 'Kobrahaltung'),
  ('concentration-curl', 'de', 'Konzentrationscurl'),
  ('corpse-pose', 'de', 'Totenhaltung'),
  ('cossack-squat', 'de', 'Kosakenkniebeuge'),
  ('cow-face-pose', 'de', 'Kuhkopfhaltung'),
  ('crescent-lunge', 'de', 'Halbmond-Ausfallschritt'),
  ('cross-body-crunch', 'de', 'Diagonaler Crunch'),
  ('cross-body-hammer-curl', 'de', 'Hammercurl über den Körper'),
  ('cross-body-shoulder-stretch', 'de', 'Schulterdehnung über den Körper'),
  ('crow-pose', 'de', 'Krähenhaltung'),
  ('dancer-pose', 'de', 'Tänzerhaltung'),
  ('dead-bug', 'de', 'Dead Bug'),
  ('dead-bug-hold', 'de', 'Dead Bug halten'),
  ('dead-hang', 'de', 'Passives Hängen'),
  ('deadlift', 'de', 'Kreuzheben'),
  ('decline-barbell-bench-press', 'de', 'Negativ-Bankdrücken mit der Langhantel'),
  ('decline-bench-press', 'de', 'Negativ-Bankdrücken'),
  ('decline-crunch', 'de', 'Crunch auf der Negativbank'),
  ('decline-dumbbell-fly', 'de', 'Fliegende auf der Negativbank mit Kurzhanteln'),
  ('decline-ez-bar-bench-press', 'de', 'Negativ-Bankdrücken mit der SZ-Stange'),
  ('decline-push-up', 'de', 'Liegestütz mit erhöhten Füßen'),
  ('deficit-deadlift', 'de', 'Kreuzheben vom Podest'),
  ('deficit-push-ups', 'de', 'Liegestütze mit erhöhten Händen'),
  ('diamond-push-ups', 'de', 'Diamant-Liegestütze'),
  ('dolphin-pose', 'de', 'Delfinhaltung'),
  ('donkey-calf-raise', 'de', 'Eselwadenheben'),
  ('doorway-chest-stretch', 'de', 'Brustdehnung im Türrahmen'),
  ('double-dumbbell-overhead-carry', 'de', 'Überkopftragen mit zwei Kurzhanteln'),
  ('double-kettlebell-bicep-curl', 'de', 'Bizepscurl mit zwei Kettlebells'),
  ('double-kettlebell-clean', 'de', 'Umsetzen mit zwei Kettlebells'),
  ('double-kettlebell-clean-and-press', 'de', 'Umsetzen und Drücken mit zwei Kettlebells'),
  ('double-kettlebell-jerk', 'de', 'Stoßen mit zwei Kettlebells'),
  ('double-kettlebell-overhead-carry', 'de', 'Überkopftragen mit zwei Kettlebells'),
  ('double-kettlebell-overhead-press', 'de', 'Überkopfdrücken mit zwei Kettlebells'),
  ('double-kettlebell-push-press', 'de', 'Push Press mit zwei Kettlebells'),
  ('double-kettlebell-rear-delt-row', 'de', 'Rudern für die hintere Schulter mit zwei Kettlebells'),
  ('double-kettlebell-row', 'de', 'Rudern mit zwei Kettlebells'),
  ('double-kettlebell-split-jerk', 'de', 'Stoßen in den Ausfallschritt mit zwei Kettlebells'),
  ('downward-dog-to-low-lunge', 'de', 'Herabschauender Hund in den tiefen Ausfallschritt'),
  ('downward-dog-to-plank', 'de', 'Herabschauender Hund in den Stütz'),
  ('downward-dog-to-upward-dog', 'de', 'Herabschauender Hund in den heraufschauenden Hund'),
  ('downward-facing-dog', 'de', 'Herabschauender Hund'),
  ('drag-curl', 'de', 'Drag Curl'),
  ('dragon-flag', 'de', 'Dragon Flag'),
  ('dumbbell-bench-press', 'de', 'Kurzhantel-Bankdrücken'),
  ('dumbbell-calf-raise', 'de', 'Wadenheben mit Kurzhanteln'),
  ('dumbbell-deadlift', 'de', 'Kreuzheben mit Kurzhanteln'),
  ('dumbbell-face-pull', 'de', 'Face Pull mit Kurzhanteln'),
  ('dumbbell-farmer-s-walk', 'de', 'Farmer''s Walk mit Kurzhanteln'),
  ('dumbbell-floor-press', 'de', 'Floor Press mit Kurzhanteln'),
  ('dumbbell-fly', 'de', 'Fliegende mit Kurzhanteln'),
  ('dumbbell-front-raise', 'de', 'Frontheben mit Kurzhanteln'),
  ('dumbbell-front-squat', 'de', 'Frontkniebeuge mit Kurzhanteln'),
  ('dumbbell-hip-thrust', 'de', 'Hip Thrust mit Kurzhantel'),
  ('dumbbell-lunge', 'de', 'Ausfallschritt mit Kurzhanteln'),
  ('dumbbell-overhead-carry', 'de', 'Überkopftragen mit Kurzhantel'),
  ('dumbbell-pistol-squat', 'de', 'Pistol Squat mit Kurzhantel'),
  ('dumbbell-pullover', 'de', 'Überzüge mit Kurzhantel'),
  ('dumbbell-push-press', 'de', 'Push Press mit Kurzhanteln'),
  ('dumbbell-reverse-curl', 'de', 'Reverse Curl mit Kurzhanteln'),
  ('dumbbell-reverse-fly', 'de', 'Reverse Fliegende mit Kurzhanteln'),
  ('dumbbell-reverse-wrist-curl', 'de', 'Umgekehrter Handgelenkcurl mit Kurzhanteln'),
  ('dumbbell-romanian-deadlift', 'de', 'Rumänisches Kreuzheben mit Kurzhanteln'),
  ('dumbbell-shrug', 'de', 'Schulterheben mit Kurzhanteln'),
  ('dumbbell-side-bend', 'de', 'Seitbeuge mit Kurzhantel'),
  ('dumbbell-skull-crusher', 'de', 'Stirndrücken mit Kurzhanteln'),
  ('dumbbell-snatch', 'de', 'Reißen mit der Kurzhantel'),
  ('dumbbell-split-squat', 'de', 'Split-Kniebeuge mit Kurzhanteln'),
  ('dumbbell-squat', 'de', 'Kniebeuge mit Kurzhanteln'),
  ('dumbbell-sumo-squat', 'de', 'Sumo-Kniebeuge mit Kurzhantel'),
  ('dumbbell-tricep-extension', 'de', 'Trizepsstrecken mit Kurzhantel'),
  ('dumbbell-tricep-kickback', 'de', 'Trizeps-Kickback mit Kurzhanteln'),
  ('dumbbell-upright-row', 'de', 'Aufrechtes Rudern mit Kurzhanteln'),
  ('dumbbell-windmill', 'de', 'Windmühle mit Kurzhantel'),
  ('dumbbell-wrist-curl', 'de', 'Handgelenkcurl mit Kurzhanteln'),
  ('eagle-pose', 'de', 'Adlerhaltung'),
  ('easy-pose', 'de', 'Schneidersitz'),
  ('elliptical', 'de', 'Crosstrainer'),
  ('extended-side-angle-pose', 'de', 'Gestreckte Seitwinkelhaltung'),
  ('ez-bar-bench-press', 'de', 'Bankdrücken mit der SZ-Stange'),
  ('ez-bar-curl', 'de', 'SZ-Curl'),
  ('ez-bar-front-raise', 'de', 'Frontheben mit der SZ-Stange'),
  ('ez-bar-lying-triceps-extension', 'de', 'Liegendes Trizepsstrecken mit der SZ-Stange'),
  ('ez-bar-overhead-tricep-extension', 'de', 'Überkopf-Trizepsstrecken mit der SZ-Stange'),
  ('ez-bar-pullover', 'de', 'Überzüge mit der SZ-Stange'),
  ('ez-bar-reverse-curl', 'de', 'Reverse Curl mit der SZ-Stange'),
  ('ez-bar-reverse-grip-row', 'de', 'Rudern im Untergriff mit der SZ-Stange'),
  ('ez-bar-romanian-deadlift', 'de', 'Rumänisches Kreuzheben mit der SZ-Stange'),
  ('ez-bar-shrug', 'de', 'Schulterheben mit der SZ-Stange'),
  ('ez-bar-spider-curl', 'de', 'Spider Curl mit der SZ-Stange'),
  ('ez-bar-upright-row', 'de', 'Aufrechtes Rudern mit der SZ-Stange'),
  ('ez-bar-wrist-curl', 'de', 'Handgelenkcurl mit der SZ-Stange'),
  ('face-pull', 'de', 'Face Pull'),
  ('fish-pose', 'de', 'Fischhaltung'),
  ('floor-ez-bar-press', 'de', 'Floor Press mit der SZ-Stange'),
  ('floor-kettlebell-pullover', 'de', 'Überzüge am Boden mit der Kettlebell'),
  ('floor-press', 'de', 'Floor Press'),
  ('flutter-kicks', 'de', 'Beinflattern'),
  ('front-lever', 'de', 'Front Lever'),
  ('front-squat', 'de', 'Frontkniebeuge'),
  ('garland-pose', 'de', 'Girlandenhaltung'),
  ('glute-bridge', 'de', 'Beckenheben'),
  ('glute-bridge-hold', 'de', 'Beckenheben halten'),
  ('glute-kickback', 'de', 'Beinrückheben'),
  ('glute-kickback-hold', 'de', 'Beinrückheben halten'),
  ('goblet-squat', 'de', 'Goblet-Kniebeuge'),
  ('good-morning', 'de', 'Good Morning'),
  ('hack-squat', 'de', 'Hackenschmidt-Kniebeuge'),
  ('hack-squat-calf-raise', 'de', 'Wadenheben an der Hackenschmidt-Maschine'),
  ('half-moon-pose', 'de', 'Halbmondhaltung'),
  ('hammer-curl', 'de', 'Hammercurl'),
  ('handstand-push-ups', 'de', 'Handstand-Liegestütze'),
  ('hang-clean', 'de', 'Umsetzen aus dem Hang'),
  ('hang-power-clean', 'de', 'Power-Umsetzen aus dem Hang'),
  ('hanging-knee-raise', 'de', 'Hängendes Knieheben'),
  ('hanging-leg-raise', 'de', 'Hängendes Beinheben'),
  ('happy-baby-pose', 'de', 'Haltung des glücklichen Babys'),
  ('head-to-knee-pose', 'de', 'Kopf-zum-Knie-Haltung'),
  ('heel-elevated-squat', 'de', 'Kniebeuge mit erhöhten Fersen'),
  ('heel-to-toe-walk', 'de', 'Fersen-Zehen-Gang'),
  ('hero-pose', 'de', 'Heldenhaltung'),
  ('hex-bar-deadlift', 'de', 'Kreuzheben mit der Hexbar'),
  ('high-foot-leg-press', 'de', 'Beinpresse mit hoher Fußstellung'),
  ('high-knees', 'de', 'Kniehebelauf'),
  ('high-plank', 'de', 'Hoher Stütz'),
  ('hip-abduction', 'de', 'Hüftabduktion'),
  ('hip-adduction', 'de', 'Hüftadduktion'),
  ('hip-thrust', 'de', 'Hip Thrust'),
  ('hollow-body-hold', 'de', 'Hollow Body halten'),
  ('horizontal-leg-press', 'de', 'Horizontale Beinpresse'),
  ('human-flag', 'de', 'Human Flag'),
  ('incline-barbell-bench-press', 'de', 'Schrägbankdrücken mit der Langhantel'),
  ('incline-dumbbell-curl', 'de', 'Bizepscurl auf der Schrägbank'),
  ('incline-dumbbell-fly', 'de', 'Fliegende auf der Schrägbank'),
  ('incline-dumbbell-press', 'de', 'Schrägbankdrücken mit Kurzhanteln'),
  ('incline-ez-bar-bench-press', 'de', 'Schrägbankdrücken mit der SZ-Stange'),
  ('incline-hammer-curl', 'de', 'Hammercurl auf der Schrägbank'),
  ('incline-push-up', 'de', 'Liegestütz mit erhöhten Händen'),
  ('incline-treadmill-walk', 'de', 'Gehen am Laufband mit Steigung'),
  ('inverted-row', 'de', 'Umgekehrtes Rudern'),
  ('isometric-neck-lateral-flexion', 'de', 'Isometrische seitliche Nackenbeugung'),
  ('jackknife-sit-up', 'de', 'Klappmesser'),
  ('jump-rope', 'de', 'Seilspringen'),
  ('jump-squat', 'de', 'Sprungkniebeuge'),
  ('jumping-jacks', 'de', 'Hampelmann'),
  ('kettlebell-bulgarian-split-squat', 'de', 'Bulgarische Kniebeuge mit der Kettlebell'),
  ('kettlebell-close-grip-floor-press', 'de', 'Enges Floor Press mit der Kettlebell'),
  ('kettlebell-concentration-curl', 'de', 'Konzentrationscurl mit der Kettlebell'),
  ('kettlebell-deadlift', 'de', 'Kreuzheben mit der Kettlebell'),
  ('kettlebell-farmer-s-walk', 'de', 'Farmer''s Walk mit Kettlebells'),
  ('kettlebell-floor-press', 'de', 'Floor Press mit der Kettlebell'),
  ('kettlebell-goblet-lunge', 'de', 'Goblet-Ausfallschritt mit der Kettlebell'),
  ('kettlebell-halo', 'de', 'Kettlebell-Halo'),
  ('kettlebell-hammer-curl', 'de', 'Hammercurl mit der Kettlebell'),
  ('kettlebell-hip-thrust', 'de', 'Hip Thrust mit der Kettlebell'),
  ('kettlebell-overhead-carry', 'de', 'Überkopftragen mit der Kettlebell'),
  ('kettlebell-overhead-tricep-extension', 'de', 'Überkopf-Trizepsstrecken mit der Kettlebell'),
  ('kettlebell-pistol-squat', 'de', 'Pistol Squat mit der Kettlebell'),
  ('kettlebell-pullover', 'de', 'Überzüge mit der Kettlebell'),
  ('kettlebell-reverse-lunge', 'de', 'Rückwärtiger Ausfallschritt mit der Kettlebell'),
  ('kettlebell-reverse-wrist-curl', 'de', 'Umgekehrter Handgelenkcurl mit der Kettlebell'),
  ('kettlebell-rotational-lunge', 'de', 'Ausfallschritt mit Rotation und Kettlebell'),
  ('kettlebell-russian-twist', 'de', 'Russischer Twist mit der Kettlebell'),
  ('kettlebell-shrug', 'de', 'Schulterheben mit Kettlebells'),
  ('kettlebell-single-leg-deadlift', 'de', 'Einbeiniges Kreuzheben mit der Kettlebell'),
  ('kettlebell-skull-crusher', 'de', 'Stirndrücken mit der Kettlebell'),
  ('kettlebell-squat', 'de', 'Kniebeuge mit der Kettlebell'),
  ('kettlebell-sumo-deadlift', 'de', 'Sumo-Kreuzheben mit der Kettlebell'),
  ('kettlebell-sumo-high-pull', 'de', 'Sumo High Pull mit der Kettlebell'),
  ('kettlebell-svend-press', 'de', 'Svend Press mit der Kettlebell'),
  ('kettlebell-swing', 'de', 'Kettlebell Swing'),
  ('kettlebell-swing-clean', 'de', 'Swing-Umsetzen mit der Kettlebell'),
  ('kettlebell-turkish-get-ups', 'de', 'Türkisches Aufstehen mit der Kettlebell'),
  ('kettlebell-windmills', 'de', 'Windmühlen mit der Kettlebell'),
  ('kettlebell-wrist-curl', 'de', 'Handgelenkcurl mit der Kettlebell'),
  ('knee-push-ups', 'de', 'Liegestütze auf den Knien'),
  ('knee-to-chest-stretch', 'de', 'Knie-zur-Brust-Dehnung'),
  ('kneeling-cable-row', 'de', 'Kniendes Rudern am Kabelzug'),
  ('kneeling-hip-flexor-stretch', 'de', 'Hüftbeugerdehnung im Kniestand'),
  ('kneeling-wrist-stretch', 'de', 'Handgelenkdehnung im Kniestand'),
  ('l-sit', 'de', 'L-Sitz'),
  ('landmine-press', 'de', 'Landmine Press'),
  ('lat-pulldown', 'de', 'Latzug'),
  ('lateral-raise', 'de', 'Seitheben'),
  ('leg-curl', 'de', 'Beinbeuger'),
  ('leg-extension', 'de', 'Beinstrecker'),
  ('leg-press', 'de', 'Beinpresse'),
  ('legs-up-the-wall-pose', 'de', 'Beine an der Wand'),
  ('lizard-stretch', 'de', 'Eidechsenhaltung'),
  ('locust-pose', 'de', 'Heuschreckenhaltung'),
  ('low-lunge', 'de', 'Tiefer Ausfallschritt'),
  ('low-lunge-to-half-split', 'de', 'Tiefer Ausfallschritt in den halben Spagat'),
  ('lunge', 'de', 'Ausfallschritt'),
  ('lying-leg-raise', 'de', 'Liegendes Beinheben'),
  ('lying-tricep-extension', 'de', 'Liegendes Trizepsstrecken'),
  ('machine-assisted-dips', 'de', 'Dips an der Maschine mit Unterstützung'),
  ('machine-back-extension', 'de', 'Rückenstrecken an der Maschine'),
  ('machine-bicep-curl', 'de', 'Bizepscurl an der Maschine'),
  ('machine-chest-fly', 'de', 'Butterfly an der Maschine'),
  ('machine-preacher-curl', 'de', 'Scottcurl an der Maschine'),
  ('machine-seated-crunch', 'de', 'Sitzender Crunch an der Maschine'),
  ('machine-shoulder-press', 'de', 'Schulterdrücken an der Maschine'),
  ('machine-triceps-extension', 'de', 'Trizepsstrecken an der Maschine'),
  ('medicine-ball-slam', 'de', 'Medizinball-Slam'),
  ('mountain-climbers', 'de', 'Bergsteiger'),
  ('mountain-pose', 'de', 'Berghaltung'),
  ('muscle-ups', 'de', 'Muscle-ups'),
  ('neck-side-stretch', 'de', 'Seitliche Nackendehnung'),
  ('negative-pull-ups', 'de', 'Negative Klimmzüge'),
  ('neutral-grip-pull-ups', 'de', 'Klimmzüge im Neutralgriff'),
  ('nordic-curl', 'de', 'Nordic Curl'),
  ('one-arm-dumbbell-push-press', 'de', 'Einarmiges Push Press mit der Kurzhantel'),
  ('one-arm-dumbbell-swing', 'de', 'Einarmiger Swing mit der Kurzhantel'),
  ('one-arm-kettlebell-bicep-curl', 'de', 'Einarmiger Bizepscurl mit der Kettlebell'),
  ('one-arm-kettlebell-bottoms-up-press', 'de', 'Einarmiges Bottoms-Up-Drücken mit der Kettlebell'),
  ('one-arm-kettlebell-floor-press', 'de', 'Einarmiges Floor Press mit der Kettlebell'),
  ('one-arm-kettlebell-front-squat', 'de', 'Einarmige Frontkniebeuge mit der Kettlebell'),
  ('one-arm-kettlebell-push-press', 'de', 'Einarmiges Push Press mit der Kettlebell'),
  ('one-arm-kettlebell-row', 'de', 'Einarmiges Rudern mit der Kettlebell'),
  ('one-arm-kettlebell-shoulder-press', 'de', 'Einarmiges Schulterdrücken mit der Kettlebell'),
  ('one-arm-kettlebell-swing', 'de', 'Einarmiger Kettlebell Swing'),
  ('one-arm-kettlebell-tricep-kickback', 'de', 'Einarmiger Trizeps-Kickback mit der Kettlebell'),
  ('one-arm-landmine-press', 'de', 'Einarmiges Landmine Press'),
  ('one-arm-lat-pulldown', 'de', 'Einarmiger Latzug'),
  ('one-arm-single-leg-dumbbell-romanian-deadlift', 'de', 'Einarmiges einbeiniges rumänisches Kreuzheben mit der Kurzhantel'),
  ('one-arm-single-leg-kettlebell-romanian-deadlift', 'de', 'Einarmiges einbeiniges rumänisches Kreuzheben mit der Kettlebell'),
  ('overhead-press', 'de', 'Überkopfdrücken'),
  ('overhead-squat', 'de', 'Überkopfkniebeuge'),
  ('overhead-tricep-extension', 'de', 'Überkopf-Trizepsstrecken'),
  ('overhead-triceps-stretch', 'de', 'Überkopf-Trizepsdehnung'),
  ('pause-deadlift', 'de', 'Kreuzheben mit Pause'),
  ('pause-pull-up', 'de', 'Klimmzug mit Pause'),
  ('pause-squat', 'de', 'Kniebeuge mit Pause'),
  ('paused-bench-press', 'de', 'Bankdrücken mit Pause'),
  ('paused-incline-bench-press', 'de', 'Schrägbankdrücken mit Pause'),
  ('paused-overhead-press', 'de', 'Überkopfdrücken mit Pause'),
  ('pec-deck', 'de', 'Butterfly'),
  ('pendlay-row', 'de', 'Pendlay Row'),
  ('pigeon-stretch', 'de', 'Taubenhaltung'),
  ('pike-push-ups', 'de', 'Pike-Liegestütze'),
  ('pilates-kneeling-side-kick', 'de', 'Pilates Side Kick im Kniestand'),
  ('pilates-leg-pull-back', 'de', 'Pilates Leg Pull Back'),
  ('pilates-leg-pull-front', 'de', 'Pilates Leg Pull Front'),
  ('pilates-roll-down', 'de', 'Pilates Roll Down'),
  ('pilates-roll-over', 'de', 'Pilates Roll Over'),
  ('pilates-saw', 'de', 'Pilates Säge'),
  ('pilates-side-bend', 'de', 'Pilates Seitbeuge'),
  ('pilates-spine-stretch-forward', 'de', 'Pilates Wirbelsäulendehnung vorwärts'),
  ('pilates-spine-twist', 'de', 'Pilates Wirbelsäulendrehung'),
  ('pistol-squat', 'de', 'Pistol Squat'),
  ('planche', 'de', 'Planche'),
  ('plank', 'de', 'Unterarmstütz'),
  ('plate-loaded-donkey-calf-raise', 'de', 'Eselwadenheben mit Scheibenaufnahme'),
  ('plate-loaded-lateral-raise', 'de', 'Seitheben an der Maschine mit Scheibenaufnahme'),
  ('plate-loaded-shrug', 'de', 'Schulterheben an der Maschine mit Scheibenaufnahme'),
  ('plate-pinch', 'de', 'Scheibenklemmen'),
  ('plate-pullover', 'de', 'Überzüge mit der Hantelscheibe'),
  ('plow-pose', 'de', 'Pflughaltung'),
  ('plyo-lunge', 'de', 'Sprungausfallschritt'),
  ('plyo-push-up', 'de', 'Plyometrischer Liegestütz'),
  ('preacher-curl', 'de', 'Scottcurl'),
  ('preacher-hammer-curl', 'de', 'Hammercurl am Scottpult'),
  ('pseudo-planche-push-ups', 'de', 'Pseudo-Planche-Liegestütze'),
  ('pull-up', 'de', 'Klimmzug'),
  ('puppy-pose', 'de', 'Welpenhaltung'),
  ('push-jerk', 'de', 'Push Jerk'),
  ('push-press', 'de', 'Push Press'),
  ('push-up', 'de', 'Liegestütz'),
  ('pyramid-pose', 'de', 'Pyramidenhaltung'),
  ('rack-pull', 'de', 'Rack Pull'),
  ('rear-delt-fly', 'de', 'Reverse Butterfly'),
  ('reverse-crunches', 'de', 'Umgekehrte Crunches'),
  ('reverse-curl', 'de', 'Reverse Curl'),
  ('reverse-grip-bent-over-row', 'de', 'Vorgebeugtes Rudern im Untergriff'),
  ('reverse-grip-lat-pulldown', 'de', 'Latzug im Untergriff'),
  ('reverse-lunge', 'de', 'Rückwärtiger Ausfallschritt'),
  ('reverse-nordic-curl', 'de', 'Reverse Nordic Curl'),
  ('reverse-plank', 'de', 'Umgekehrter Stütz'),
  ('reverse-plank-dips', 'de', 'Dips im umgekehrten Stütz'),
  ('reverse-tabletop-hip-pulses', 'de', 'Hüftpulsieren im umgekehrten Tisch'),
  ('reverse-tabletop-hold', 'de', 'Umgekehrten Tisch halten'),
  ('revolved-chair-pose', 'de', 'Gedrehte Stuhlhaltung'),
  ('revolved-crescent-lunge', 'de', 'Gedrehter Halbmond-Ausfallschritt'),
  ('ring-dead-hang', 'de', 'Passives Hängen an den Ringen'),
  ('ring-dips', 'de', 'Dips an den Ringen'),
  ('ring-face-pull', 'de', 'Face Pull an den Ringen'),
  ('ring-muscle-up', 'de', 'Muscle-up an den Ringen'),
  ('ring-push-up', 'de', 'Liegestütz an den Ringen'),
  ('ring-row', 'de', 'Rudern an den Ringen'),
  ('rings-inverted-row', 'de', 'Umgekehrtes Rudern an den Ringen'),
  ('romanian-deadlift', 'de', 'Rumänisches Kreuzheben'),
  ('rope-climb', 'de', 'Seilklettern'),
  ('rowing-machine', 'de', 'Ruderergometer'),
  ('running', 'de', 'Laufen'),
  ('russian-twist', 'de', 'Russischer Twist'),
  ('scapular-pull-ups', 'de', 'Skapula-Klimmzüge'),
  ('scissor-kicks', 'de', 'Beinscheren'),
  ('seated-barbell-overhead-press', 'de', 'Sitzendes Überkopfdrücken mit der Langhantel'),
  ('seated-calf-raise', 'de', 'Sitzendes Wadenheben'),
  ('seated-dumbbell-curl', 'de', 'Sitzender Bizepscurl mit Kurzhanteln'),
  ('seated-dumbbell-lateral-raise', 'de', 'Sitzendes Seitheben mit Kurzhanteln'),
  ('seated-dumbbell-shoulder-press', 'de', 'Sitzendes Schulterdrücken mit Kurzhanteln'),
  ('seated-dumbbell-tricep-extension', 'de', 'Sitzendes Trizepsstrecken mit Kurzhantel'),
  ('seated-forward-fold', 'de', 'Sitzende Vorbeuge'),
  ('seated-leg-curl', 'de', 'Sitzender Beinbeuger'),
  ('seated-row', 'de', 'Sitzendes Rudern'),
  ('seated-smith-machine-shoulder-press', 'de', 'Sitzendes Schulterdrücken an der Multipresse'),
  ('seated-spinal-twist', 'de', 'Sitzender Drehsitz'),
  ('seated-straddle-stretch', 'de', 'Sitzende Grätsche'),
  ('shoulder-press', 'de', 'Schulterdrücken'),
  ('side-lunge', 'de', 'Seitlicher Ausfallschritt'),
  ('side-lying-hip-abduction', 'de', 'Hüftabduktion in Seitlage'),
  ('side-lying-hip-abduction-hold', 'de', 'Hüftabduktion in Seitlage halten'),
  ('side-lying-hip-adduction', 'de', 'Hüftadduktion in Seitlage'),
  ('side-lying-hip-adduction-hold', 'de', 'Hüftadduktion in Seitlage halten'),
  ('side-lying-lateral-raise', 'de', 'Seitheben in Seitlage'),
  ('side-plank', 'de', 'Seitstütz'),
  ('side-plank-leg-lift-hold', 'de', 'Seitstütz mit angehobenem Bein halten'),
  ('side-plank-with-leg-lift', 'de', 'Seitstütz mit Beinheben'),
  ('single-arm-chest-supported-dumbbell-row', 'de', 'Einarmiges Kurzhantelrudern mit Brustauflage'),
  ('single-arm-dumbbell-overhead-tricep-extension', 'de', 'Einarmiges Überkopf-Trizepsstrecken mit der Kurzhantel'),
  ('single-arm-dumbbell-row', 'de', 'Einarmiges Kurzhantelrudern'),
  ('single-arm-hammer-curl', 'de', 'Einarmiger Hammercurl'),
  ('single-arm-machine-shoulder-press', 'de', 'Einarmiges Schulterdrücken an der Maschine'),
  ('single-arm-plate-loaded-lateral-raise', 'de', 'Einarmiges Seitheben an der Maschine mit Scheibenaufnahme'),
  ('single-arm-tricep-pushdown', 'de', 'Einarmiges Trizepsdrücken am Kabelzug'),
  ('single-dumbbell-svend-press', 'de', 'Svend Press mit einer Kurzhantel'),
  ('single-leg-calf-raise', 'de', 'Einbeiniges Wadenheben'),
  ('single-leg-extension', 'de', 'Einbeiniger Beinstrecker'),
  ('single-leg-glute-bridge', 'de', 'Einbeiniges Beckenheben'),
  ('single-leg-glute-bridge-hold', 'de', 'Einbeiniges Beckenheben halten'),
  ('single-leg-lying-leg-curl', 'de', 'Einbeiniger liegender Beinbeuger'),
  ('single-leg-press', 'de', 'Einbeinige Beinpresse'),
  ('single-leg-romanian-deadlift', 'de', 'Einbeiniges rumänisches Kreuzheben'),
  ('sit-ups', 'de', 'Sit-ups'),
  ('ski-erg', 'de', 'Ski-Ergometer'),
  ('skull-crusher', 'de', 'Stirndrücken'),
  ('sled-row', 'de', 'Rudern am Schlitten'),
  ('smith-machine', 'de', 'Multipresse'),
  ('smith-machine-bench-press', 'de', 'Bankdrücken an der Multipresse'),
  ('smith-machine-bent-over-row', 'de', 'Vorgebeugtes Rudern an der Multipresse'),
  ('smith-machine-bulgarian-split-squat', 'de', 'Bulgarische Kniebeuge an der Multipresse'),
  ('smith-machine-calf-raise', 'de', 'Wadenheben an der Multipresse'),
  ('smith-machine-decline-bench-press', 'de', 'Negativ-Bankdrücken an der Multipresse'),
  ('smith-machine-front-squat', 'de', 'Frontkniebeuge an der Multipresse'),
  ('smith-machine-good-morning', 'de', 'Good Morning an der Multipresse'),
  ('smith-machine-hip-thrust', 'de', 'Hip Thrust an der Multipresse'),
  ('smith-machine-incline-bench-press', 'de', 'Schrägbankdrücken an der Multipresse'),
  ('smith-machine-reverse-grip-bent-over-row', 'de', 'Vorgebeugtes Rudern im Untergriff an der Multipresse'),
  ('smith-machine-reverse-lunge', 'de', 'Rückwärtiger Ausfallschritt an der Multipresse'),
  ('smith-machine-romanian-deadlift', 'de', 'Rumänisches Kreuzheben an der Multipresse'),
  ('smith-machine-shoulder-press', 'de', 'Schulterdrücken an der Multipresse'),
  ('smith-machine-shrug', 'de', 'Schulterheben an der Multipresse'),
  ('smith-machine-split-squat', 'de', 'Split-Kniebeuge an der Multipresse'),
  ('smith-machine-squat', 'de', 'Kniebeuge an der Multipresse'),
  ('smith-machine-upright-row', 'de', 'Aufrechtes Rudern an der Multipresse'),
  ('snatch', 'de', 'Reißen'),
  ('sphinx-pose', 'de', 'Sphinxhaltung'),
  ('spider-curl', 'de', 'Spider Curl'),
  ('split-jerk', 'de', 'Stoßen in den Ausfallschritt'),
  ('split-squat', 'de', 'Split-Kniebeuge'),
  ('spoto-press', 'de', 'Spoto Press'),
  ('stability-ball-hip-bridge', 'de', 'Beckenheben am Gymnastikball'),
  ('stability-ball-knee-tuck', 'de', 'Knieanziehen am Gymnastikball'),
  ('stability-ball-push-up', 'de', 'Liegestütz am Gymnastikball'),
  ('stability-ball-push-up-hands-on-ball', 'de', 'Liegestütz mit den Händen auf dem Gymnastikball'),
  ('stability-ball-wall-squat', 'de', 'Wandkniebeuge mit dem Gymnastikball'),
  ('stair-climber', 'de', 'Treppensteiger'),
  ('standing-calf-raise', 'de', 'Stehendes Wadenheben'),
  ('standing-calf-stretch', 'de', 'Stehende Wadendehnung'),
  ('standing-forward-fold', 'de', 'Stehende Vorbeuge'),
  ('standing-forward-fold-to-half-lift', 'de', 'Stehende Vorbeuge zum halben Aufrichten'),
  ('standing-quad-stretch', 'de', 'Stehende Quadrizepsdehnung'),
  ('standing-side-bend', 'de', 'Stehende Seitbeuge'),
  ('standing-split', 'de', 'Stehender Spagat'),
  ('step-ups', 'de', 'Step-ups'),
  ('stiff-leg-deadlift', 'de', 'Gestrecktes Kreuzheben'),
  ('straight-arm-pulldown', 'de', 'Latziehen mit gestreckten Armen'),
  ('straight-bar-cable-front-raise', 'de', 'Frontheben am Kabelzug mit der Stange'),
  ('straight-bar-dips', 'de', 'Dips an der geraden Stange'),
  ('strict-curl', 'de', 'Strict Curl'),
  ('suitcase-carry', 'de', 'Koffertragen'),
  ('sumo-deadlift', 'de', 'Sumo-Kreuzheben'),
  ('sumo-squat', 'de', 'Sumo-Kniebeuge'),
  ('superman', 'de', 'Superman'),
  ('supine-spinal-twist', 'de', 'Wirbelsäulendrehung in Rückenlage'),
  ('supine-windshield-wipers', 'de', 'Scheibenwischer in Rückenlage'),
  ('supported-shoulderstand', 'de', 'Gestützter Schulterstand'),
  ('svend-press', 'de', 'Svend Press'),
  ('t-bar-row', 'de', 'T-Bar-Rudern'),
  ('thoracic-bridge', 'de', 'Thorakale Brücke'),
  ('thread-the-needle', 'de', 'Nadel einfädeln'),
  ('three-legged-downward-dog', 'de', 'Dreibeiniger herabschauender Hund'),
  ('thruster', 'de', 'Thruster'),
  ('toes-to-bar', 'de', 'Zehen zur Stange'),
  ('treadmill', 'de', 'Laufband'),
  ('tree-pose', 'de', 'Baumhaltung'),
  ('triangle-pose', 'de', 'Dreieckshaltung'),
  ('tricep-pushdown', 'de', 'Trizepsdrücken'),
  ('trx-bicep-curl', 'de', 'Bizepscurl am TRX'),
  ('trx-chest-press', 'de', 'Brustdrücken am TRX'),
  ('trx-face-pull', 'de', 'Face Pull am TRX'),
  ('trx-hamstring-curl', 'de', 'Beinbeuger am TRX'),
  ('trx-lunge', 'de', 'Ausfallschritt am TRX'),
  ('trx-pistol-squat', 'de', 'Pistol Squat am TRX'),
  ('trx-plank', 'de', 'Unterarmstütz am TRX'),
  ('trx-row', 'de', 'Rudern am TRX'),
  ('trx-side-plank', 'de', 'Seitstütz am TRX'),
  ('trx-squat', 'de', 'Kniebeuge am TRX'),
  ('trx-triceps-extension', 'de', 'Trizepsstrecken am TRX'),
  ('trx-y-fly', 'de', 'Y-Fly am TRX'),
  ('upright-bike', 'de', 'Fahrradergometer'),
  ('upward-facing-dog', 'de', 'Heraufschauender Hund'),
  ('v-bar-lat-pulldown', 'de', 'Latzug mit dem V-Griff'),
  ('v-bar-tricep-pushdown', 'de', 'Trizepsdrücken mit dem V-Griff'),
  ('v-sit', 'de', 'V-Sitz'),
  ('v-ups', 'de', 'V-Ups'),
  ('walking', 'de', 'Gehen'),
  ('walking-lunge', 'de', 'Gehender Ausfallschritt'),
  ('wall-push-ups', 'de', 'Liegestütze an der Wand'),
  ('wall-sit', 'de', 'Wandsitz'),
  ('warrior-i', 'de', 'Krieger I'),
  ('warrior-ii', 'de', 'Krieger II'),
  ('warrior-iii', 'de', 'Krieger III'),
  ('weighted-dips', 'de', 'Dips mit Zusatzgewicht'),
  ('weighted-pull-up', 'de', 'Klimmzug mit Zusatzgewicht'),
  ('weighted-wall-crunch', 'de', 'Crunch an der Wand mit Zusatzgewicht'),
  ('wide-grip-bench-press', 'de', 'Bankdrücken im weiten Griff'),
  ('wide-grip-pull-ups', 'de', 'Klimmzüge im weiten Griff'),
  ('wide-grip-push-ups', 'de', 'Weite Liegestütze'),
  ('wide-grip-seated-cable-row', 'de', 'Sitzendes Rudern am Kabelzug im weiten Griff'),
  ('wide-legged-forward-fold', 'de', 'Grätschstand-Vorbeuge'),
  ('wide-stance-leg-press', 'de', 'Beinpresse mit weitem Stand'),
  ('wrist-roller', 'de', 'Unterarmroller'),
  ('zottman-curl', 'de', 'Zottman-Curl'),
  ('downward-dog-knee-tuck', 'de', 'Herabschauender Hund mit Knieanziehen'),
  ('downward-dog-pedal', 'de', 'Herabschauender Hund mit Fersendrücken'),
  ('dumbbell-svend-press', 'de', 'Svend Press mit Kurzhanteln'),
  ('half-kneeling-hip-flexor-rock', 'de', 'Hüftbeuger-Wippen im halben Kniestand'),
  ('jefferson-curl', 'de', 'Jefferson Curl'),
  ('muscle-snatch', 'de', 'Muscle Snatch'),
  ('plate-loaded-glute-drive', 'de', 'Glute Drive mit Scheibenaufnahme')
on conflict (exercise_id, locale) do update
  set name = excluded.name,
      source = excluded.source,
      updated_at = now();
