-- ─────────────────────────────────────────────────────────────────────────
-- The catalogue in Spanish: 583 of 604 movements.
--
-- The same set part 791 translates into German, translated into Spanish. Part
-- 790 argues the schema; this file's decisions are all about words.
--
-- ── Why this says 604 and not 619 ─────────────────────────────────────────
--
-- The same sixteen rows part 791 lost, lost here for the same reason and with
-- the same ids — see that file's header for the full argument. In short:
-- written against the 619-row catalogue a fresh database builds, applied
-- against a production catalogue of 604 that never held fifteen of the ids,
-- and exercise_id is a foreign key, so the insert aborted on the first of them.
--
-- Fifteen were duplicates whose surviving partner is already translated below
-- ('bench-press' carries press de banca; the removed 'barbell-bench-press' said
-- press de banca con barra for a movement whose name is "Bench Press"). The
-- sixteenth, 'stability-ball-leg-curl', is one movement RepDB renamed between
-- two generations — production calls it 'ball-leg-curl' — so no literal id here
-- is right on both databases, and part 2310 writes it by lookup instead.
--
-- The one consequence worth naming: 'cable-kickback' now has no Spanish, its
-- translated partner having been the removed 'cable-glute-kickback'. That is
-- correct — it is one of the twenty below.
--
-- ── Gym Spanish, not translated English ───────────────────────────────────
--
--   · Bench Press is press de banca. Deadlift is peso muerto — "levantamiento
--     muerto" is what a translator produces and what nobody says.
--   · A Lat Pulldown is a jalón al pecho; behind the neck it is a jalón tras
--     nuca. Neither contains the word for "pulldown".
--   · An Upright Row is a remo al mentón — named for where the bar finishes,
--     not for the torso being upright.
--   · A Skull Crusher and a Lying Triceps Extension are both press francés.
--     Two English names, one Spanish one, and pretending otherwise would
--     invent a distinction Spanish lifters do not make.
--   · A Preacher Curl is a curl en banco Scott, an EZ-bar is a barra Z, a
--     Smith machine is a máquina Smith, and a Pec Deck is a contractor de
--     pecho.
--   · Clean and Snatch are cargada and arrancada — the platform words.
--
-- ── One Spanish, and it is not pretending to be two ───────────────────────
--
-- Regional gym vocabulary genuinely differs: a lunge is a zancada in Spain and
-- often a desplante in Mexico. This ships ONE Spanish, so an es-MX handset
-- reads the same rows an es-ES one does — see catalogueLocale(), which matches
-- on the language subtag alone and says why. That is honest. What would not be
-- honest is claiming a regional match we have not done; if es-MX is ever worth
-- shipping it arrives as its own locale, not as a quiet widening of this one.
--
-- Where a term is regional and a neutral one exists, the neutral one is used:
-- "elevación de talones" rather than a local word for calf work, "prensa de
-- piernas" rather than the several names the leg press machine has.
--
-- ── Where the Spanish name IS the English one ─────────────────────────────
--
-- Face pull, burpees, thruster, planche, rack pull, push press, kettlebell.
-- These carry a row with the English words, because that is what is said in a
-- Spanish gym — a positive claim, not an absence. See part 791's header for
-- why the two must not be conflated.
--
-- ── The same 20 stay English ──────────────────────────────────────────────
--
-- Identical list to part 791 and for the same reason: no settled term, or an
-- English name that is itself ambiguous about which movement it is. Guessing
-- one would put somebody on the wrong machine.
--
-- Re-running upserts on (exercise_id, locale); nothing is deleted. Descriptions
-- are not translated here — see part 791.
-- ─────────────────────────────────────────────────────────────────────────

insert into public.exercise_translations (exercise_id, locale, name) values
  ('ab-crunch', 'es', 'Crunch abdominal'),
  ('ab-wheel-rollout', 'es', 'Rueda abdominal'),
  ('air-bike', 'es', 'Bicicleta de aire'),
  ('archer-pull-ups', 'es', 'Dominadas de arquero'),
  ('archer-push-ups', 'es', 'Flexiones de arquero'),
  ('arnold-press', 'es', 'Press Arnold'),
  ('assisted-pull-up', 'es', 'Dominada asistida'),
  ('back-extension', 'es', 'Hiperextensión lumbar'),
  ('back-lever', 'es', 'Back lever'),
  ('back-squat', 'es', 'Sentadilla trasera'),
  ('band-assisted-pull-ups', 'es', 'Dominadas con banda'),
  ('band-pull-apart', 'es', 'Separaciones con banda elástica'),
  ('banded-adductor-stretch', 'es', 'Estiramiento de aductores con banda'),
  ('banded-ankle-stretch', 'es', 'Estiramiento de tobillo con banda'),
  ('banded-calf-stretch', 'es', 'Estiramiento de gemelos con banda'),
  ('banded-chest-stretch', 'es', 'Estiramiento de pecho con banda'),
  ('banded-clamshell', 'es', 'Almeja con banda'),
  ('banded-figure-4-stretch', 'es', 'Estiramiento en cuatro con banda'),
  ('banded-fire-hydrant', 'es', 'Abducción de cadera en cuadrupedia con banda'),
  ('banded-glute-bridge', 'es', 'Puente de glúteos con banda'),
  ('banded-good-morning', 'es', 'Buenos días con banda'),
  ('banded-hamstring-stretch', 'es', 'Estiramiento de isquiotibiales con banda'),
  ('banded-hip-thrust', 'es', 'Empuje de cadera con banda'),
  ('banded-it-band-stretch', 'es', 'Estiramiento de la banda iliotibial con banda'),
  ('banded-kneeling-hip-thrust', 'es', 'Empuje de cadera de rodillas con banda'),
  ('banded-lat-stretch', 'es', 'Estiramiento de dorsales con banda'),
  ('banded-lateral-walk', 'es', 'Caminata lateral con banda'),
  ('banded-rear-delt-stretch', 'es', 'Estiramiento del deltoides posterior con banda'),
  ('banded-romanian-deadlift', 'es', 'Peso muerto rumano con banda'),
  ('banded-seated-hip-abduction', 'es', 'Abducción de cadera sentado con banda'),
  ('banded-shoulder-stretch', 'es', 'Estiramiento de hombro con banda'),
  ('banded-squat', 'es', 'Sentadilla con banda'),
  ('banded-standing-hip-abduction', 'es', 'Abducción de cadera de pie con banda'),
  ('banded-standing-hip-adduction', 'es', 'Aducción de cadera de pie con banda'),
  ('banded-standing-leg-curl', 'es', 'Curl femoral de pie con banda'),
  ('banded-sumo-walk', 'es', 'Caminata sumo con banda'),
  ('banded-terminal-knee-extension', 'es', 'Extensión terminal de rodilla con banda'),
  ('banded-triceps-stretch', 'es', 'Estiramiento de tríceps con banda'),
  ('barbell-ab-rollout', 'es', 'Rollout abdominal con barra'),
  ('barbell-calf-raise', 'es', 'Elevación de talones con barra'),
  ('barbell-curl', 'es', 'Curl con barra'),
  ('barbell-front-raise', 'es', 'Elevación frontal con barra'),
  ('barbell-glute-bridge', 'es', 'Puente de glúteos con barra'),
  ('barbell-lunge', 'es', 'Zancada con barra'),
  ('barbell-overhead-extension', 'es', 'Extensión de tríceps sobre la cabeza con barra'),
  ('barbell-preacher-curl', 'es', 'Curl en banco Scott con barra'),
  ('barbell-pullover', 'es', 'Pullover con barra'),
  ('barbell-rear-delt-row', 'es', 'Remo para deltoides posterior con barra'),
  ('barbell-reverse-lunge', 'es', 'Zancada hacia atrás con barra'),
  ('barbell-shrug', 'es', 'Encogimiento de hombros con barra'),
  ('barbell-upright-row', 'es', 'Remo al mentón con barra'),
  ('barbell-wrist-curl', 'es', 'Curl de muñeca con barra'),
  ('battle-rope-double-slam', 'es', 'Golpe doble con cuerdas de batalla'),
  ('battle-ropes', 'es', 'Cuerdas de batalla'),
  ('bear-crawl', 'es', 'Marcha del oso'),
  ('behind-the-back-barbell-shrug', 'es', 'Encogimiento de hombros con barra por detrás'),
  ('behind-the-neck-lat-pulldown', 'es', 'Jalón tras nuca'),
  ('behind-the-neck-press', 'es', 'Press tras nuca'),
  ('behind-the-neck-pull-up', 'es', 'Dominada tras nuca'),
  ('bench-adductor-stretch', 'es', 'Estiramiento de aductores en banco'),
  ('bench-ankle-stretch', 'es', 'Estiramiento de tobillo en banco'),
  ('bench-bulgarian-split-stretch', 'es', 'Estiramiento en split búlgaro con banco'),
  ('bench-calf-stretch', 'es', 'Estiramiento de gemelos en banco'),
  ('bench-chest-stretch', 'es', 'Estiramiento de pecho en banco'),
  ('bench-child-s-pose', 'es', 'Postura del niño con banco'),
  ('bench-couch-stretch', 'es', 'Estiramiento de sofá con banco'),
  ('bench-dips', 'es', 'Fondos en banco'),
  ('bench-figure-4-glute-stretch', 'es', 'Estiramiento de glúteo en cuatro con banco'),
  ('bench-hamstring-stretch', 'es', 'Estiramiento de isquiotibiales en banco'),
  ('bench-lat-stretch', 'es', 'Estiramiento de dorsales en banco'),
  ('bench-leg-pull-in', 'es', 'Encogimiento de piernas en banco'),
  ('bench-press', 'es', 'Press de banca'),
  ('bench-pull', 'es', 'Remo tumbado en banco'),
  ('bent-arm-barbell-pullover', 'es', 'Pullover con barra y brazos flexionados'),
  ('bent-arm-ez-bar-pullover', 'es', 'Pullover con barra Z y brazos flexionados'),
  ('bent-over-dumbbell-row', 'es', 'Remo con mancuernas'),
  ('bent-over-ez-bar-row', 'es', 'Remo con barra Z'),
  ('bent-over-row', 'es', 'Remo inclinado'),
  ('bicep-curl', 'es', 'Curl de bíceps'),
  ('bicycle-crunch', 'es', 'Crunch bicicleta'),
  ('bilateral-dumbbell-wrist-curl', 'es', 'Curl de muñeca con mancuernas a dos manos'),
  ('bird-dog', 'es', 'Bird dog'),
  ('bird-dog-hold', 'es', 'Bird dog isométrico'),
  ('boat-pose', 'es', 'Postura del barco'),
  ('bodyweight-calf-raise', 'es', 'Elevación de talones con peso corporal'),
  ('bodyweight-good-morning', 'es', 'Buenos días con peso corporal'),
  ('bodyweight-lateral-raise', 'es', 'Elevación lateral sin peso'),
  ('bodyweight-overhead-press', 'es', 'Press sobre la cabeza sin peso'),
  ('bodyweight-reverse-lunge', 'es', 'Zancada hacia atrás con peso corporal'),
  ('bodyweight-squat', 'es', 'Sentadilla con peso corporal'),
  ('bow-pose', 'es', 'Postura del arco'),
  ('box-jump', 'es', 'Salto al cajón'),
  ('box-squat', 'es', 'Sentadilla al cajón'),
  ('bulgarian-split-squat', 'es', 'Sentadilla búlgara'),
  ('burpees', 'es', 'Burpees'),
  ('butterfly-stretch', 'es', 'Estiramiento de mariposa'),
  ('cable-bent-over-row', 'es', 'Remo inclinado en polea'),
  ('cable-chest-press', 'es', 'Press de pecho en polea'),
  ('cable-crossover', 'es', 'Cruce de poleas'),
  ('cable-crunch', 'es', 'Crunch en polea'),
  ('cable-curl', 'es', 'Curl en polea'),
  ('cable-external-rotation', 'es', 'Rotación externa en polea'),
  ('cable-front-raise', 'es', 'Elevación frontal en polea'),
  ('cable-hammer-curl', 'es', 'Curl martillo en polea'),
  ('cable-lateral-raise', 'es', 'Elevación lateral en polea'),
  ('cable-machine', 'es', 'Máquina de poleas'),
  ('cable-pallof-press', 'es', 'Press Pallof en polea'),
  ('cable-tricep-kickback', 'es', 'Patada de tríceps en polea'),
  ('cable-upright-row', 'es', 'Remo al mentón en polea'),
  ('cable-wrist-curl', 'es', 'Curl de muñeca en polea'),
  ('calf-raise', 'es', 'Elevación de talones'),
  ('camel-pose', 'es', 'Postura del camello'),
  ('captain-s-chair-knee-raise', 'es', 'Elevación de rodillas en silla romana'),
  ('captain-s-chair-leg-raise', 'es', 'Elevación de piernas en silla romana'),
  ('cat-cow', 'es', 'Gato-vaca'),
  ('cat-stretch', 'es', 'Estiramiento del gato'),
  ('chair-pose', 'es', 'Postura de la silla'),
  ('cheat-curl', 'es', 'Curl con impulso'),
  ('chest-dips', 'es', 'Fondos para pecho'),
  ('chest-press', 'es', 'Press de pecho'),
  ('chest-supported-dumbbell-row', 'es', 'Remo con mancuernas con apoyo de pecho'),
  ('chest-supported-dumbbell-shrug', 'es', 'Encogimiento de hombros con mancuernas con apoyo de pecho'),
  ('chest-supported-kettlebell-row', 'es', 'Remo con kettlebell con apoyo de pecho'),
  ('chest-supported-smith-machine-row', 'es', 'Remo en máquina Smith con apoyo de pecho'),
  ('child-s-pose', 'es', 'Postura del niño'),
  ('chin-ups', 'es', 'Dominadas supinas'),
  ('clamshell-hold', 'es', 'Almeja isométrica'),
  ('clamshells', 'es', 'Almejas'),
  ('clap-push-ups', 'es', 'Flexiones con palmada'),
  ('clean', 'es', 'Cargada'),
  ('clean-and-jerk', 'es', 'Cargada y envión'),
  ('close-grip-barbell-curl', 'es', 'Curl con barra agarre cerrado'),
  ('close-grip-bench-press', 'es', 'Press de banca agarre cerrado'),
  ('close-grip-dumbbell-bench-press', 'es', 'Press de banca con mancuernas agarre cerrado'),
  ('close-grip-ez-bar-bench-press', 'es', 'Press de banca con barra Z agarre cerrado'),
  ('close-grip-ez-bar-curl', 'es', 'Curl con barra Z agarre cerrado'),
  ('close-grip-incline-bench-press', 'es', 'Press inclinado agarre cerrado'),
  ('close-grip-lat-pulldown', 'es', 'Jalón agarre cerrado'),
  ('close-grip-pull-ups', 'es', 'Dominadas agarre cerrado'),
  ('close-grip-push-ups', 'es', 'Flexiones agarre cerrado'),
  ('close-stance-leg-press', 'es', 'Prensa de piernas con pies juntos'),
  ('cobra-stretch', 'es', 'Postura de la cobra'),
  ('concentration-curl', 'es', 'Curl concentrado'),
  ('corpse-pose', 'es', 'Postura del cadáver'),
  ('cossack-squat', 'es', 'Sentadilla cosaca'),
  ('cow-face-pose', 'es', 'Postura de la cara de vaca'),
  ('crescent-lunge', 'es', 'Zancada en media luna'),
  ('cross-body-crunch', 'es', 'Crunch cruzado'),
  ('cross-body-hammer-curl', 'es', 'Curl martillo cruzado'),
  ('cross-body-shoulder-stretch', 'es', 'Estiramiento de hombro cruzado'),
  ('crow-pose', 'es', 'Postura del cuervo'),
  ('dancer-pose', 'es', 'Postura del bailarín'),
  ('dead-bug', 'es', 'Dead bug'),
  ('dead-bug-hold', 'es', 'Dead bug isométrico'),
  ('dead-hang', 'es', 'Colgado pasivo'),
  ('deadlift', 'es', 'Peso muerto'),
  ('decline-barbell-bench-press', 'es', 'Press de banca declinado con barra'),
  ('decline-bench-press', 'es', 'Press de banca declinado'),
  ('decline-crunch', 'es', 'Crunch en banco declinado'),
  ('decline-dumbbell-fly', 'es', 'Aperturas declinadas con mancuernas'),
  ('decline-ez-bar-bench-press', 'es', 'Press de banca declinado con barra Z'),
  ('decline-push-up', 'es', 'Flexión declinada'),
  ('deficit-deadlift', 'es', 'Peso muerto en déficit'),
  ('deficit-push-ups', 'es', 'Flexiones en déficit'),
  ('diamond-push-ups', 'es', 'Flexiones diamante'),
  ('dolphin-pose', 'es', 'Postura del delfín'),
  ('donkey-calf-raise', 'es', 'Elevación de talones tipo burro'),
  ('doorway-chest-stretch', 'es', 'Estiramiento de pecho en el marco de la puerta'),
  ('double-dumbbell-overhead-carry', 'es', 'Transporte sobre la cabeza con dos mancuernas'),
  ('double-kettlebell-bicep-curl', 'es', 'Curl de bíceps con dos kettlebells'),
  ('double-kettlebell-clean', 'es', 'Cargada con dos kettlebells'),
  ('double-kettlebell-clean-and-press', 'es', 'Cargada y press con dos kettlebells'),
  ('double-kettlebell-jerk', 'es', 'Envión con dos kettlebells'),
  ('double-kettlebell-overhead-carry', 'es', 'Transporte sobre la cabeza con dos kettlebells'),
  ('double-kettlebell-overhead-press', 'es', 'Press sobre la cabeza con dos kettlebells'),
  ('double-kettlebell-push-press', 'es', 'Push press con dos kettlebells'),
  ('double-kettlebell-rear-delt-row', 'es', 'Remo para deltoides posterior con dos kettlebells'),
  ('double-kettlebell-row', 'es', 'Remo con dos kettlebells'),
  ('double-kettlebell-split-jerk', 'es', 'Envión en tijera con dos kettlebells'),
  ('downward-dog-to-low-lunge', 'es', 'Perro boca abajo a zancada baja'),
  ('downward-dog-to-plank', 'es', 'Perro boca abajo a plancha'),
  ('downward-dog-to-upward-dog', 'es', 'Perro boca abajo a perro boca arriba'),
  ('downward-facing-dog', 'es', 'Perro boca abajo'),
  ('drag-curl', 'es', 'Curl de arrastre'),
  ('dragon-flag', 'es', 'Bandera del dragón'),
  ('dumbbell-bench-press', 'es', 'Press de banca con mancuernas'),
  ('dumbbell-calf-raise', 'es', 'Elevación de talones con mancuernas'),
  ('dumbbell-deadlift', 'es', 'Peso muerto con mancuernas'),
  ('dumbbell-face-pull', 'es', 'Face pull con mancuernas'),
  ('dumbbell-farmer-s-walk', 'es', 'Paseo del granjero con mancuernas'),
  ('dumbbell-floor-press', 'es', 'Press en el suelo con mancuernas'),
  ('dumbbell-fly', 'es', 'Aperturas con mancuernas'),
  ('dumbbell-front-raise', 'es', 'Elevación frontal con mancuernas'),
  ('dumbbell-front-squat', 'es', 'Sentadilla frontal con mancuernas'),
  ('dumbbell-hip-thrust', 'es', 'Empuje de cadera con mancuerna'),
  ('dumbbell-lunge', 'es', 'Zancada con mancuernas'),
  ('dumbbell-overhead-carry', 'es', 'Transporte sobre la cabeza con mancuerna'),
  ('dumbbell-pistol-squat', 'es', 'Sentadilla pistol con mancuerna'),
  ('dumbbell-pullover', 'es', 'Pullover con mancuerna'),
  ('dumbbell-push-press', 'es', 'Push press con mancuernas'),
  ('dumbbell-reverse-curl', 'es', 'Curl inverso con mancuernas'),
  ('dumbbell-reverse-fly', 'es', 'Aperturas invertidas con mancuernas'),
  ('dumbbell-reverse-wrist-curl', 'es', 'Curl de muñeca inverso con mancuernas'),
  ('dumbbell-romanian-deadlift', 'es', 'Peso muerto rumano con mancuernas'),
  ('dumbbell-shrug', 'es', 'Encogimiento de hombros con mancuernas'),
  ('dumbbell-side-bend', 'es', 'Flexión lateral con mancuerna'),
  ('dumbbell-skull-crusher', 'es', 'Press francés con mancuernas'),
  ('dumbbell-snatch', 'es', 'Arrancada con mancuerna'),
  ('dumbbell-split-squat', 'es', 'Sentadilla dividida con mancuernas'),
  ('dumbbell-squat', 'es', 'Sentadilla con mancuernas'),
  ('dumbbell-sumo-squat', 'es', 'Sentadilla sumo con mancuerna'),
  ('dumbbell-tricep-extension', 'es', 'Extensión de tríceps con mancuerna'),
  ('dumbbell-tricep-kickback', 'es', 'Patada de tríceps con mancuernas'),
  ('dumbbell-upright-row', 'es', 'Remo al mentón con mancuernas'),
  ('dumbbell-windmill', 'es', 'Molino con mancuerna'),
  ('dumbbell-wrist-curl', 'es', 'Curl de muñeca con mancuernas'),
  ('eagle-pose', 'es', 'Postura del águila'),
  ('easy-pose', 'es', 'Postura fácil'),
  ('elliptical', 'es', 'Elíptica'),
  ('extended-side-angle-pose', 'es', 'Postura del ángulo lateral extendido'),
  ('ez-bar-bench-press', 'es', 'Press de banca con barra Z'),
  ('ez-bar-curl', 'es', 'Curl con barra Z'),
  ('ez-bar-front-raise', 'es', 'Elevación frontal con barra Z'),
  ('ez-bar-lying-triceps-extension', 'es', 'Press francés tumbado con barra Z'),
  ('ez-bar-overhead-tricep-extension', 'es', 'Extensión de tríceps sobre la cabeza con barra Z'),
  ('ez-bar-pullover', 'es', 'Pullover con barra Z'),
  ('ez-bar-reverse-curl', 'es', 'Curl inverso con barra Z'),
  ('ez-bar-reverse-grip-row', 'es', 'Remo supino con barra Z'),
  ('ez-bar-romanian-deadlift', 'es', 'Peso muerto rumano con barra Z'),
  ('ez-bar-shrug', 'es', 'Encogimiento de hombros con barra Z'),
  ('ez-bar-spider-curl', 'es', 'Curl araña con barra Z'),
  ('ez-bar-upright-row', 'es', 'Remo al mentón con barra Z'),
  ('ez-bar-wrist-curl', 'es', 'Curl de muñeca con barra Z'),
  ('face-pull', 'es', 'Face pull'),
  ('fish-pose', 'es', 'Postura del pez'),
  ('floor-ez-bar-press', 'es', 'Press en el suelo con barra Z'),
  ('floor-kettlebell-pullover', 'es', 'Pullover en el suelo con kettlebell'),
  ('floor-press', 'es', 'Press en el suelo'),
  ('flutter-kicks', 'es', 'Aleteo de piernas'),
  ('front-lever', 'es', 'Front lever'),
  ('front-squat', 'es', 'Sentadilla frontal'),
  ('garland-pose', 'es', 'Postura de la guirnalda'),
  ('glute-bridge', 'es', 'Puente de glúteos'),
  ('glute-bridge-hold', 'es', 'Puente de glúteos isométrico'),
  ('glute-kickback', 'es', 'Patada de glúteo'),
  ('glute-kickback-hold', 'es', 'Patada de glúteo isométrica'),
  ('goblet-squat', 'es', 'Sentadilla goblet'),
  ('good-morning', 'es', 'Buenos días'),
  ('hack-squat', 'es', 'Sentadilla hack'),
  ('hack-squat-calf-raise', 'es', 'Elevación de talones en máquina hack'),
  ('half-moon-pose', 'es', 'Postura de la media luna'),
  ('hammer-curl', 'es', 'Curl martillo'),
  ('handstand-push-ups', 'es', 'Flexiones en pino'),
  ('hang-clean', 'es', 'Cargada desde suspensión'),
  ('hang-power-clean', 'es', 'Cargada de potencia desde suspensión'),
  ('hanging-knee-raise', 'es', 'Elevación de rodillas colgado'),
  ('hanging-leg-raise', 'es', 'Elevación de piernas colgado'),
  ('happy-baby-pose', 'es', 'Postura del bebé feliz'),
  ('head-to-knee-pose', 'es', 'Postura de cabeza a rodilla'),
  ('heel-elevated-squat', 'es', 'Sentadilla con talones elevados'),
  ('heel-to-toe-walk', 'es', 'Marcha talón-punta'),
  ('hero-pose', 'es', 'Postura del héroe'),
  ('hex-bar-deadlift', 'es', 'Peso muerto con barra hexagonal'),
  ('high-foot-leg-press', 'es', 'Prensa de piernas con pies altos'),
  ('high-knees', 'es', 'Rodillas altas'),
  ('high-plank', 'es', 'Plancha alta'),
  ('hip-abduction', 'es', 'Abducción de cadera'),
  ('hip-adduction', 'es', 'Aducción de cadera'),
  ('hip-thrust', 'es', 'Empuje de cadera'),
  ('hollow-body-hold', 'es', 'Hollow body isométrico'),
  ('horizontal-leg-press', 'es', 'Prensa de piernas horizontal'),
  ('human-flag', 'es', 'Bandera humana'),
  ('incline-barbell-bench-press', 'es', 'Press inclinado con barra'),
  ('incline-dumbbell-curl', 'es', 'Curl inclinado con mancuernas'),
  ('incline-dumbbell-fly', 'es', 'Aperturas inclinadas con mancuernas'),
  ('incline-dumbbell-press', 'es', 'Press inclinado con mancuernas'),
  ('incline-ez-bar-bench-press', 'es', 'Press inclinado con barra Z'),
  ('incline-hammer-curl', 'es', 'Curl martillo inclinado'),
  ('incline-push-up', 'es', 'Flexión inclinada'),
  ('incline-treadmill-walk', 'es', 'Caminata en cinta con inclinación'),
  ('inverted-row', 'es', 'Remo invertido'),
  ('isometric-neck-lateral-flexion', 'es', 'Flexión lateral isométrica de cuello'),
  ('jackknife-sit-up', 'es', 'Navaja abdominal'),
  ('jump-rope', 'es', 'Saltar a la comba'),
  ('jump-squat', 'es', 'Sentadilla con salto'),
  ('jumping-jacks', 'es', 'Saltos de tijera'),
  ('kettlebell-bulgarian-split-squat', 'es', 'Sentadilla búlgara con kettlebell'),
  ('kettlebell-close-grip-floor-press', 'es', 'Press en el suelo con agarre cerrado con kettlebell'),
  ('kettlebell-concentration-curl', 'es', 'Curl concentrado con kettlebell'),
  ('kettlebell-deadlift', 'es', 'Peso muerto con kettlebell'),
  ('kettlebell-farmer-s-walk', 'es', 'Paseo del granjero con kettlebells'),
  ('kettlebell-floor-press', 'es', 'Press en el suelo con kettlebell'),
  ('kettlebell-goblet-lunge', 'es', 'Zancada goblet con kettlebell'),
  ('kettlebell-halo', 'es', 'Halo con kettlebell'),
  ('kettlebell-hammer-curl', 'es', 'Curl martillo con kettlebell'),
  ('kettlebell-hip-thrust', 'es', 'Empuje de cadera con kettlebell'),
  ('kettlebell-overhead-carry', 'es', 'Transporte sobre la cabeza con kettlebell'),
  ('kettlebell-overhead-tricep-extension', 'es', 'Extensión de tríceps sobre la cabeza con kettlebell'),
  ('kettlebell-pistol-squat', 'es', 'Sentadilla pistol con kettlebell'),
  ('kettlebell-pullover', 'es', 'Pullover con kettlebell'),
  ('kettlebell-reverse-lunge', 'es', 'Zancada hacia atrás con kettlebell'),
  ('kettlebell-reverse-wrist-curl', 'es', 'Curl de muñeca inverso con kettlebell'),
  ('kettlebell-rotational-lunge', 'es', 'Zancada con rotación con kettlebell'),
  ('kettlebell-russian-twist', 'es', 'Giro ruso con kettlebell'),
  ('kettlebell-shrug', 'es', 'Encogimiento de hombros con kettlebells'),
  ('kettlebell-single-leg-deadlift', 'es', 'Peso muerto a una pierna con kettlebell'),
  ('kettlebell-skull-crusher', 'es', 'Press francés con kettlebell'),
  ('kettlebell-squat', 'es', 'Sentadilla con kettlebell'),
  ('kettlebell-sumo-deadlift', 'es', 'Peso muerto sumo con kettlebell'),
  ('kettlebell-sumo-high-pull', 'es', 'Tirón alto sumo con kettlebell'),
  ('kettlebell-svend-press', 'es', 'Press Svend con kettlebell'),
  ('kettlebell-swing', 'es', 'Swing con kettlebell'),
  ('kettlebell-swing-clean', 'es', 'Cargada en swing con kettlebell'),
  ('kettlebell-turkish-get-ups', 'es', 'Levantada turca con kettlebell'),
  ('kettlebell-windmills', 'es', 'Molinos con kettlebell'),
  ('kettlebell-wrist-curl', 'es', 'Curl de muñeca con kettlebell'),
  ('knee-push-ups', 'es', 'Flexiones de rodillas'),
  ('knee-to-chest-stretch', 'es', 'Estiramiento de rodilla al pecho'),
  ('kneeling-cable-row', 'es', 'Remo en polea de rodillas'),
  ('kneeling-hip-flexor-stretch', 'es', 'Estiramiento de flexores de cadera de rodillas'),
  ('kneeling-wrist-stretch', 'es', 'Estiramiento de muñecas de rodillas'),
  ('l-sit', 'es', 'L-sit'),
  ('landmine-press', 'es', 'Press landmine'),
  ('lat-pulldown', 'es', 'Jalón al pecho'),
  ('lateral-raise', 'es', 'Elevación lateral'),
  ('leg-curl', 'es', 'Curl femoral'),
  ('leg-extension', 'es', 'Extensión de piernas'),
  ('leg-press', 'es', 'Prensa de piernas'),
  ('legs-up-the-wall-pose', 'es', 'Postura de piernas en la pared'),
  ('lizard-stretch', 'es', 'Postura del lagarto'),
  ('locust-pose', 'es', 'Postura del saltamontes'),
  ('low-lunge', 'es', 'Zancada baja'),
  ('low-lunge-to-half-split', 'es', 'Zancada baja a medio split'),
  ('lunge', 'es', 'Zancada'),
  ('lying-leg-raise', 'es', 'Elevación de piernas tumbado'),
  ('lying-tricep-extension', 'es', 'Press francés tumbado'),
  ('machine-assisted-dips', 'es', 'Fondos asistidos en máquina'),
  ('machine-back-extension', 'es', 'Extensión lumbar en máquina'),
  ('machine-bicep-curl', 'es', 'Curl de bíceps en máquina'),
  ('machine-chest-fly', 'es', 'Aperturas en máquina'),
  ('machine-preacher-curl', 'es', 'Curl en banco Scott en máquina'),
  ('machine-seated-crunch', 'es', 'Crunch sentado en máquina'),
  ('machine-shoulder-press', 'es', 'Press de hombro en máquina'),
  ('machine-triceps-extension', 'es', 'Extensión de tríceps en máquina'),
  ('medicine-ball-slam', 'es', 'Golpe con balón medicinal'),
  ('mountain-climbers', 'es', 'Escaladores'),
  ('mountain-pose', 'es', 'Postura de la montaña'),
  ('muscle-ups', 'es', 'Muscle ups'),
  ('neck-side-stretch', 'es', 'Estiramiento lateral de cuello'),
  ('negative-pull-ups', 'es', 'Dominadas negativas'),
  ('neutral-grip-pull-ups', 'es', 'Dominadas con agarre neutro'),
  ('nordic-curl', 'es', 'Curl nórdico'),
  ('one-arm-dumbbell-push-press', 'es', 'Push press a una mano con mancuerna'),
  ('one-arm-dumbbell-swing', 'es', 'Swing a una mano con mancuerna'),
  ('one-arm-kettlebell-bicep-curl', 'es', 'Curl de bíceps a una mano con kettlebell'),
  ('one-arm-kettlebell-bottoms-up-press', 'es', 'Press bottoms up a una mano con kettlebell'),
  ('one-arm-kettlebell-floor-press', 'es', 'Press en el suelo a una mano con kettlebell'),
  ('one-arm-kettlebell-front-squat', 'es', 'Sentadilla frontal a una mano con kettlebell'),
  ('one-arm-kettlebell-push-press', 'es', 'Push press a una mano con kettlebell'),
  ('one-arm-kettlebell-row', 'es', 'Remo a una mano con kettlebell'),
  ('one-arm-kettlebell-shoulder-press', 'es', 'Press de hombro a una mano con kettlebell'),
  ('one-arm-kettlebell-swing', 'es', 'Swing a una mano con kettlebell'),
  ('one-arm-kettlebell-tricep-kickback', 'es', 'Patada de tríceps a una mano con kettlebell'),
  ('one-arm-landmine-press', 'es', 'Press landmine a una mano'),
  ('one-arm-lat-pulldown', 'es', 'Jalón a una mano'),
  ('one-arm-single-leg-dumbbell-romanian-deadlift', 'es', 'Peso muerto rumano a una pierna y una mano con mancuerna'),
  ('one-arm-single-leg-kettlebell-romanian-deadlift', 'es', 'Peso muerto rumano a una pierna y una mano con kettlebell'),
  ('overhead-press', 'es', 'Press militar'),
  ('overhead-squat', 'es', 'Sentadilla con barra sobre la cabeza'),
  ('overhead-tricep-extension', 'es', 'Extensión de tríceps sobre la cabeza'),
  ('overhead-triceps-stretch', 'es', 'Estiramiento de tríceps sobre la cabeza'),
  ('pause-deadlift', 'es', 'Peso muerto con pausa'),
  ('pause-pull-up', 'es', 'Dominada con pausa'),
  ('pause-squat', 'es', 'Sentadilla con pausa'),
  ('paused-bench-press', 'es', 'Press de banca con pausa'),
  ('paused-incline-bench-press', 'es', 'Press inclinado con pausa'),
  ('paused-overhead-press', 'es', 'Press militar con pausa'),
  ('pec-deck', 'es', 'Contractor de pecho'),
  ('pendlay-row', 'es', 'Remo Pendlay'),
  ('pigeon-stretch', 'es', 'Postura de la paloma'),
  ('pike-push-ups', 'es', 'Flexiones pike'),
  ('pilates-kneeling-side-kick', 'es', 'Patada lateral de rodillas de Pilates'),
  ('pilates-leg-pull-back', 'es', 'Leg pull back de Pilates'),
  ('pilates-leg-pull-front', 'es', 'Leg pull front de Pilates'),
  ('pilates-roll-down', 'es', 'Roll down de Pilates'),
  ('pilates-roll-over', 'es', 'Roll over de Pilates'),
  ('pilates-saw', 'es', 'Sierra de Pilates'),
  ('pilates-side-bend', 'es', 'Flexión lateral de Pilates'),
  ('pilates-spine-stretch-forward', 'es', 'Estiramiento de columna hacia delante de Pilates'),
  ('pilates-spine-twist', 'es', 'Giro de columna de Pilates'),
  ('pistol-squat', 'es', 'Sentadilla pistol'),
  ('planche', 'es', 'Planche'),
  ('plank', 'es', 'Plancha'),
  ('plate-loaded-donkey-calf-raise', 'es', 'Elevación de talones tipo burro con discos'),
  ('plate-loaded-lateral-raise', 'es', 'Elevación lateral en máquina de discos'),
  ('plate-loaded-shrug', 'es', 'Encogimiento de hombros en máquina de discos'),
  ('plate-pinch', 'es', 'Pinza de discos'),
  ('plate-pullover', 'es', 'Pullover con disco'),
  ('plow-pose', 'es', 'Postura del arado'),
  ('plyo-lunge', 'es', 'Zancada pliométrica'),
  ('plyo-push-up', 'es', 'Flexión pliométrica'),
  ('preacher-curl', 'es', 'Curl en banco Scott'),
  ('preacher-hammer-curl', 'es', 'Curl martillo en banco Scott'),
  ('pseudo-planche-push-ups', 'es', 'Flexiones pseudo planche'),
  ('pull-up', 'es', 'Dominada'),
  ('puppy-pose', 'es', 'Postura del cachorro'),
  ('push-jerk', 'es', 'Push jerk'),
  ('push-press', 'es', 'Push press'),
  ('push-up', 'es', 'Flexión'),
  ('pyramid-pose', 'es', 'Postura de la pirámide'),
  ('rack-pull', 'es', 'Rack pull'),
  ('rear-delt-fly', 'es', 'Aperturas para deltoides posterior'),
  ('reverse-crunches', 'es', 'Crunch inverso'),
  ('reverse-curl', 'es', 'Curl inverso'),
  ('reverse-grip-bent-over-row', 'es', 'Remo inclinado supino'),
  ('reverse-grip-lat-pulldown', 'es', 'Jalón supino'),
  ('reverse-lunge', 'es', 'Zancada hacia atrás'),
  ('reverse-nordic-curl', 'es', 'Curl nórdico inverso'),
  ('reverse-plank', 'es', 'Plancha inversa'),
  ('reverse-plank-dips', 'es', 'Fondos en plancha inversa'),
  ('reverse-tabletop-hip-pulses', 'es', 'Pulsos de cadera en mesa invertida'),
  ('reverse-tabletop-hold', 'es', 'Mesa invertida isométrica'),
  ('revolved-chair-pose', 'es', 'Postura de la silla con torsión'),
  ('revolved-crescent-lunge', 'es', 'Zancada en media luna con torsión'),
  ('ring-dead-hang', 'es', 'Colgado pasivo en anillas'),
  ('ring-dips', 'es', 'Fondos en anillas'),
  ('ring-face-pull', 'es', 'Face pull en anillas'),
  ('ring-muscle-up', 'es', 'Muscle up en anillas'),
  ('ring-push-up', 'es', 'Flexión en anillas'),
  ('ring-row', 'es', 'Remo en anillas'),
  ('rings-inverted-row', 'es', 'Remo invertido en anillas'),
  ('romanian-deadlift', 'es', 'Peso muerto rumano'),
  ('rope-climb', 'es', 'Trepa de cuerda'),
  ('rowing-machine', 'es', 'Máquina de remo'),
  ('running', 'es', 'Correr'),
  ('russian-twist', 'es', 'Giro ruso'),
  ('scapular-pull-ups', 'es', 'Dominadas escapulares'),
  ('scissor-kicks', 'es', 'Tijeras de piernas'),
  ('seated-barbell-overhead-press', 'es', 'Press militar sentado con barra'),
  ('seated-calf-raise', 'es', 'Elevación de talones sentado'),
  ('seated-dumbbell-curl', 'es', 'Curl sentado con mancuernas'),
  ('seated-dumbbell-lateral-raise', 'es', 'Elevación lateral sentado con mancuernas'),
  ('seated-dumbbell-shoulder-press', 'es', 'Press de hombro sentado con mancuernas'),
  ('seated-dumbbell-tricep-extension', 'es', 'Extensión de tríceps sentado con mancuerna'),
  ('seated-forward-fold', 'es', 'Flexión hacia delante sentado'),
  ('seated-leg-curl', 'es', 'Curl femoral sentado'),
  ('seated-row', 'es', 'Remo sentado'),
  ('seated-smith-machine-shoulder-press', 'es', 'Press de hombro sentado en máquina Smith'),
  ('seated-spinal-twist', 'es', 'Torsión espinal sentado'),
  ('seated-straddle-stretch', 'es', 'Estiramiento sentado con piernas abiertas'),
  ('shoulder-press', 'es', 'Press de hombro'),
  ('side-lunge', 'es', 'Zancada lateral'),
  ('side-lying-hip-abduction', 'es', 'Abducción de cadera tumbado de lado'),
  ('side-lying-hip-abduction-hold', 'es', 'Abducción de cadera tumbado de lado isométrica'),
  ('side-lying-hip-adduction', 'es', 'Aducción de cadera tumbado de lado'),
  ('side-lying-hip-adduction-hold', 'es', 'Aducción de cadera tumbado de lado isométrica'),
  ('side-lying-lateral-raise', 'es', 'Elevación lateral tumbado de lado'),
  ('side-plank', 'es', 'Plancha lateral'),
  ('side-plank-leg-lift-hold', 'es', 'Plancha lateral con elevación de pierna isométrica'),
  ('side-plank-with-leg-lift', 'es', 'Plancha lateral con elevación de pierna'),
  ('single-arm-chest-supported-dumbbell-row', 'es', 'Remo a una mano con mancuerna y apoyo de pecho'),
  ('single-arm-dumbbell-overhead-tricep-extension', 'es', 'Extensión de tríceps sobre la cabeza a una mano con mancuerna'),
  ('single-arm-dumbbell-row', 'es', 'Remo a una mano con mancuerna'),
  ('single-arm-hammer-curl', 'es', 'Curl martillo a una mano'),
  ('single-arm-machine-shoulder-press', 'es', 'Press de hombro a una mano en máquina'),
  ('single-arm-plate-loaded-lateral-raise', 'es', 'Elevación lateral a una mano en máquina de discos'),
  ('single-arm-tricep-pushdown', 'es', 'Extensión de tríceps a una mano en polea'),
  ('single-dumbbell-svend-press', 'es', 'Press Svend con una mancuerna'),
  ('single-leg-calf-raise', 'es', 'Elevación de talones a una pierna'),
  ('single-leg-extension', 'es', 'Extensión de pierna a una pierna'),
  ('single-leg-glute-bridge', 'es', 'Puente de glúteos a una pierna'),
  ('single-leg-glute-bridge-hold', 'es', 'Puente de glúteos a una pierna isométrico'),
  ('single-leg-lying-leg-curl', 'es', 'Curl femoral tumbado a una pierna'),
  ('single-leg-press', 'es', 'Prensa de piernas a una pierna'),
  ('single-leg-romanian-deadlift', 'es', 'Peso muerto rumano a una pierna'),
  ('sit-ups', 'es', 'Abdominales'),
  ('ski-erg', 'es', 'Máquina de esquí'),
  ('skull-crusher', 'es', 'Press francés'),
  ('sled-row', 'es', 'Remo con trineo'),
  ('smith-machine', 'es', 'Máquina Smith'),
  ('smith-machine-bench-press', 'es', 'Press de banca en máquina Smith'),
  ('smith-machine-bent-over-row', 'es', 'Remo inclinado en máquina Smith'),
  ('smith-machine-bulgarian-split-squat', 'es', 'Sentadilla búlgara en máquina Smith'),
  ('smith-machine-calf-raise', 'es', 'Elevación de talones en máquina Smith'),
  ('smith-machine-decline-bench-press', 'es', 'Press de banca declinado en máquina Smith'),
  ('smith-machine-front-squat', 'es', 'Sentadilla frontal en máquina Smith'),
  ('smith-machine-good-morning', 'es', 'Buenos días en máquina Smith'),
  ('smith-machine-hip-thrust', 'es', 'Empuje de cadera en máquina Smith'),
  ('smith-machine-incline-bench-press', 'es', 'Press inclinado en máquina Smith'),
  ('smith-machine-reverse-grip-bent-over-row', 'es', 'Remo inclinado supino en máquina Smith'),
  ('smith-machine-reverse-lunge', 'es', 'Zancada hacia atrás en máquina Smith'),
  ('smith-machine-romanian-deadlift', 'es', 'Peso muerto rumano en máquina Smith'),
  ('smith-machine-shoulder-press', 'es', 'Press de hombro en máquina Smith'),
  ('smith-machine-shrug', 'es', 'Encogimiento de hombros en máquina Smith'),
  ('smith-machine-split-squat', 'es', 'Sentadilla dividida en máquina Smith'),
  ('smith-machine-squat', 'es', 'Sentadilla en máquina Smith'),
  ('smith-machine-upright-row', 'es', 'Remo al mentón en máquina Smith'),
  ('snatch', 'es', 'Arrancada'),
  ('sphinx-pose', 'es', 'Postura de la esfinge'),
  ('spider-curl', 'es', 'Curl araña'),
  ('split-jerk', 'es', 'Envión en tijera'),
  ('split-squat', 'es', 'Sentadilla dividida'),
  ('spoto-press', 'es', 'Press Spoto'),
  ('stability-ball-hip-bridge', 'es', 'Puente de cadera con fitball'),
  ('stability-ball-knee-tuck', 'es', 'Encogimiento de rodillas con fitball'),
  ('stability-ball-push-up', 'es', 'Flexión con fitball'),
  ('stability-ball-push-up-hands-on-ball', 'es', 'Flexión con las manos en el fitball'),
  ('stability-ball-wall-squat', 'es', 'Sentadilla en pared con fitball'),
  ('stair-climber', 'es', 'Máquina de escaleras'),
  ('standing-calf-raise', 'es', 'Elevación de talones de pie'),
  ('standing-calf-stretch', 'es', 'Estiramiento de gemelos de pie'),
  ('standing-forward-fold', 'es', 'Flexión hacia delante de pie'),
  ('standing-forward-fold-to-half-lift', 'es', 'Flexión hacia delante de pie a media elevación'),
  ('standing-quad-stretch', 'es', 'Estiramiento de cuádriceps de pie'),
  ('standing-side-bend', 'es', 'Flexión lateral de pie'),
  ('standing-split', 'es', 'Split de pie'),
  ('step-ups', 'es', 'Subidas al cajón'),
  ('stiff-leg-deadlift', 'es', 'Peso muerto con piernas rígidas'),
  ('straight-arm-pulldown', 'es', 'Jalón con brazos extendidos'),
  ('straight-bar-cable-front-raise', 'es', 'Elevación frontal en polea con barra'),
  ('straight-bar-dips', 'es', 'Fondos en barra recta'),
  ('strict-curl', 'es', 'Curl estricto'),
  ('suitcase-carry', 'es', 'Transporte tipo maleta'),
  ('sumo-deadlift', 'es', 'Peso muerto sumo'),
  ('sumo-squat', 'es', 'Sentadilla sumo'),
  ('superman', 'es', 'Superman'),
  ('supine-spinal-twist', 'es', 'Torsión espinal tumbado'),
  ('supine-windshield-wipers', 'es', 'Limpiaparabrisas tumbado'),
  ('supported-shoulderstand', 'es', 'Postura sobre los hombros con apoyo'),
  ('svend-press', 'es', 'Press Svend'),
  ('t-bar-row', 'es', 'Remo en barra T'),
  ('thoracic-bridge', 'es', 'Puente torácico'),
  ('thread-the-needle', 'es', 'Enhebrar la aguja'),
  ('three-legged-downward-dog', 'es', 'Perro boca abajo a tres patas'),
  ('thruster', 'es', 'Thruster'),
  ('toes-to-bar', 'es', 'Pies a la barra'),
  ('treadmill', 'es', 'Cinta de correr'),
  ('tree-pose', 'es', 'Postura del árbol'),
  ('triangle-pose', 'es', 'Postura del triángulo'),
  ('tricep-pushdown', 'es', 'Extensión de tríceps en polea alta'),
  ('trx-bicep-curl', 'es', 'Curl de bíceps en TRX'),
  ('trx-chest-press', 'es', 'Press de pecho en TRX'),
  ('trx-face-pull', 'es', 'Face pull en TRX'),
  ('trx-hamstring-curl', 'es', 'Curl femoral en TRX'),
  ('trx-lunge', 'es', 'Zancada en TRX'),
  ('trx-pistol-squat', 'es', 'Sentadilla pistol en TRX'),
  ('trx-plank', 'es', 'Plancha en TRX'),
  ('trx-row', 'es', 'Remo en TRX'),
  ('trx-side-plank', 'es', 'Plancha lateral en TRX'),
  ('trx-squat', 'es', 'Sentadilla en TRX'),
  ('trx-triceps-extension', 'es', 'Extensión de tríceps en TRX'),
  ('trx-y-fly', 'es', 'Vuelo en Y en TRX'),
  ('upright-bike', 'es', 'Bicicleta estática'),
  ('upward-facing-dog', 'es', 'Perro boca arriba'),
  ('v-bar-lat-pulldown', 'es', 'Jalón con agarre en V'),
  ('v-bar-tricep-pushdown', 'es', 'Extensión de tríceps con agarre en V'),
  ('v-sit', 'es', 'V-sit'),
  ('v-ups', 'es', 'Abdominales en V'),
  ('walking', 'es', 'Caminar'),
  ('walking-lunge', 'es', 'Zancada caminando'),
  ('wall-push-ups', 'es', 'Flexiones en pared'),
  ('wall-sit', 'es', 'Sentadilla isométrica en pared'),
  ('warrior-i', 'es', 'Guerrero I'),
  ('warrior-ii', 'es', 'Guerrero II'),
  ('warrior-iii', 'es', 'Guerrero III'),
  ('weighted-dips', 'es', 'Fondos con lastre'),
  ('weighted-pull-up', 'es', 'Dominada con lastre'),
  ('weighted-wall-crunch', 'es', 'Crunch en pared con lastre'),
  ('wide-grip-bench-press', 'es', 'Press de banca agarre ancho'),
  ('wide-grip-pull-ups', 'es', 'Dominadas agarre ancho'),
  ('wide-grip-push-ups', 'es', 'Flexiones agarre ancho'),
  ('wide-grip-seated-cable-row', 'es', 'Remo sentado en polea agarre ancho'),
  ('wide-legged-forward-fold', 'es', 'Flexión hacia delante con piernas abiertas'),
  ('wide-stance-leg-press', 'es', 'Prensa de piernas con pies separados'),
  ('wrist-roller', 'es', 'Rodillo de muñeca'),
  ('zottman-curl', 'es', 'Curl Zottman'),
  ('downward-dog-knee-tuck', 'es', 'Perro boca abajo con encogimiento de rodilla'),
  ('downward-dog-pedal', 'es', 'Perro boca abajo pedaleando'),
  ('dumbbell-svend-press', 'es', 'Press Svend con mancuernas'),
  ('half-kneeling-hip-flexor-rock', 'es', 'Balanceo de flexores de cadera en medio arrodillado'),
  ('jefferson-curl', 'es', 'Jefferson curl'),
  ('muscle-snatch', 'es', 'Muscle snatch'),
  ('plate-loaded-glute-drive', 'es', 'Glute drive con discos')
on conflict (exercise_id, locale) do update
  set name = excluded.name,
      source = excluded.source,
      updated_at = now();
